##### Define variables

In [ ]:
import pandas as pd
pd.set_option('display.float_format', '{:.5f}'.format)
pd.set_option('display.max_columns', None)
import time
import importlib
import utilities
importlib.reload(utilities)
from utilities import *

:

In [ ]:
folder = './daily historical datas/'
finance = "Finance"
technology = "Technology"
health = "Healthcare"
automobile = "Automobile"

In [ ]:
Technology = { "AAPL": pd.DataFrame(), "AMZN": pd.DataFrame(), "GOOGL": pd.DataFrame(), "META": pd.DataFrame(), "MSFT": pd.DataFrame() }
Finance = { "BAC": pd.DataFrame(), "C": pd.DataFrame(), "GS": pd.DataFrame(), "JPM": pd.DataFrame(), "WFC": pd.DataFrame() }
Health = { "ABBV": pd.DataFrame(), "JNJ": pd.DataFrame(), "MRK": pd.DataFrame(), "PFE": pd.DataFrame(), "UNH": pd.DataFrame() }
Automobile = { "F": pd.DataFrame(), "GM": pd.DataFrame(), "LCID": pd.DataFrame(), "RIVN": pd.DataFrame(), "TSLA": pd.DataFrame() }

In [ ]:
TechnologyUnderlying = [ "AAPL", "AMZN", "GOOGL", "META", "MSFT" ]
FinanceUnderlying = [ "BAC", "C", "GS", "JPM", "WFC" ]
HealthUnderlying = [ "ABBV", "JNJ", "MRK", "PFE", "UNH" ]
AutomobileUnderlying = [ "F", "GM", "LCID", "RIVN", "TSLA" ]

##### Merge options dataily data and remove duplicate rows

In [6]:
for ticker, OptionsData in Technology.items():
  df_final = fusionner_fichiers(folder, technology, ticker)
  df_final = remove_duplicates(df_final)
  Technology[ticker]= df_final

INFO:utilities:174 files found for keyword: aapl

['./daily historical datas/Technology\\Tech_sector_2025-09-12\\AAPL_calls_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-12\\AAPL_puts_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\AAPL_calls_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\AAPL_puts_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\AAPL_calls_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\AAPL_puts_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\AAPL_calls_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\AAPL_puts_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\AAPL_calls_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\AAPL_puts_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\AAPL_calls_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\AAPL_puts_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\AAPL_calls_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\AAPL_puts_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\AAPL_calls_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\AAPL_puts_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\AAPL_calls_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\AAPL_puts_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\AAPL_calls_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\AAPL_puts_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\AAPL_calls_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\AAPL_puts_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\AAPL_calls_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\AAPL_puts_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\AAPL_calls_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\AAPL_puts_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\AAPL_calls_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\AAPL_puts_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\AAPL_calls_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\AAPL_puts_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\AAPL_calls_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\AAPL_puts_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\AAPL_calls_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\AAPL_puts_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\AAPL_calls_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\AAPL_puts_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\AAPL_calls_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\AAPL_puts_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\AAPL_calls_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\AAPL_puts_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\AAPL_calls_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\AAPL_puts_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\AAPL_calls_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\AAPL_puts_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\AAPL_calls_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\AAPL_puts_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\AAPL_calls_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\AAPL_puts_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\AAPL_calls_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\AAPL_puts_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\AAPL_calls_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\AAPL_puts_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\AAPL_calls_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\AAPL_puts_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\AAPL_calls_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\AAPL_puts_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\AAPL_calls_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\AAPL_puts_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\AAPL_calls_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\AAPL_puts_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\AAPL_calls_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\AAPL_puts_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\AAPL_calls_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\AAPL_puts_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\AAPL_calls_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\AAPL_puts_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\AAPL_calls_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\AAPL_puts_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\AAPL_calls_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\AAPL_puts_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\AAPL_calls_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\AAPL_puts_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\AAPL_calls_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\AAPL_puts_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\AAPL_calls_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\AAPL_puts_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\AAPL_calls_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\AAPL_puts_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\AAPL_calls_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\AAPL_puts_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\AAPL_calls_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\AAPL_puts_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\AAPL_calls_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\AAPL_puts_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\AAPL_calls_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\AAPL_puts_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\AAPL_calls_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\AAPL_puts_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\AAPL_calls_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\AAPL_puts_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\AAPL_calls_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\AAPL_puts_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\AAPL_calls_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\AAPL_puts_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\AAPL_calls_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\AAPL_puts_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\AAPL_calls_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\AAPL_puts_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\AAPL_calls_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\AAPL_puts_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\AAPL_calls_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\AAPL_puts_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\AAPL_calls_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\AAPL_puts_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\AAPL_calls_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\AAPL_puts_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\AAPL_calls_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\AAPL_puts_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\AAPL_calls_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\AAPL_puts_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\AAPL_calls_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\AAPL_puts_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\AAPL_calls_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\AAPL_puts_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\AAPL_calls_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\AAPL_puts_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\AAPL_calls_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\AAPL_puts_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\AAPL_calls_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\AAPL_puts_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\AAPL_calls_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\AAPL_puts_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\AAPL_calls_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\AAPL_puts_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\AAPL_calls_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\AAPL_puts_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\AAPL_calls_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\AAPL_puts_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\AAPL_calls_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\AAPL_puts_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\AAPL_calls_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\AAPL_puts_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\AAPL_calls_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\AAPL_puts_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\AAPL_calls_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\AAPL_puts_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\AAPL_calls_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\AAPL_puts_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\AAPL_calls_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\AAPL_puts_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\AAPL_calls_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\AAPL_puts_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\AAPL_calls_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\AAPL_puts_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\AAPL_calls_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\AAPL_puts_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\AAPL_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\AAPL_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\AAPL_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\AAPL_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\AAPL_calls_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\AAPL_puts_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\AAPL_calls_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\AAPL_puts_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\AAPL_calls_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\AAPL_puts_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\AAPL_calls_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\AAPL_puts_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\AAPL_calls_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\AAPL_puts_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\AAPL_calls_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\AAPL_puts_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\AAPL_calls_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\AAPL_puts_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\AAPL_calls_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\AAPL_puts_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\AAPL_calls_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\AAPL_puts_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\AAPL_calls_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\AAPL_puts_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\AAPL_calls_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\AAPL_puts_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\AAPL_calls_all_for_2026-01-05.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\AAPL_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (192224, 16)
INFO:utilities:Removed 84445 duplicates
INFO:utilities:174 files found for keyword: amzn

['./daily historical datas/Technology\\Tech_sector_2025-09-12\\AMZN_calls_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-12\\AMZN_puts_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\AMZN_calls_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\AMZN_puts_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\AMZN_calls_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\AMZN_puts_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\AMZN_calls_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\AMZN_puts_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\AMZN_calls_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\AMZN_puts_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\AMZN_calls_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\AMZN_puts_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\AMZN_calls_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\AMZN_puts_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\AMZN_calls_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\AMZN_puts_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\AMZN_calls_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\AMZN_puts_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\AMZN_calls_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\AMZN_puts_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\AMZN_calls_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\AMZN_puts_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\AMZN_calls_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\AMZN_puts_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\AMZN_calls_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\AMZN_puts_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\AMZN_calls_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\AMZN_puts_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\AMZN_calls_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\AMZN_puts_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\AMZN_calls_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\AMZN_puts_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\AMZN_calls_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\AMZN_puts_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\AMZN_calls_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\AMZN_puts_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\AMZN_calls_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\AMZN_puts_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\AMZN_calls_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\AMZN_puts_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\AMZN_calls_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\AMZN_puts_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\AMZN_calls_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\AMZN_puts_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\AMZN_calls_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\AMZN_puts_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\AMZN_calls_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\AMZN_puts_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\AMZN_calls_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\AMZN_puts_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\AMZN_calls_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\AMZN_puts_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\AMZN_calls_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\AMZN_puts_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\AMZN_calls_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\AMZN_puts_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\AMZN_calls_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\AMZN_puts_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\AMZN_calls_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\AMZN_puts_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\AMZN_calls_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\AMZN_puts_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\AMZN_calls_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\AMZN_puts_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\AMZN_calls_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\AMZN_puts_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\AMZN_calls_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\AMZN_puts_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\AMZN_calls_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\AMZN_puts_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\AMZN_calls_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\AMZN_puts_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\AMZN_calls_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\AMZN_puts_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\AMZN_calls_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\AMZN_puts_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\AMZN_calls_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\AMZN_puts_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\AMZN_calls_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\AMZN_puts_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\AMZN_calls_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\AMZN_puts_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\AMZN_calls_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\AMZN_puts_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\AMZN_calls_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\AMZN_puts_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\AMZN_calls_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\AMZN_puts_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\AMZN_calls_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\AMZN_puts_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\AMZN_calls_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\AMZN_puts_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\AMZN_calls_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\AMZN_puts_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\AMZN_calls_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\AMZN_puts_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\AMZN_calls_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\AMZN_puts_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\AMZN_calls_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\AMZN_puts_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\AMZN_calls_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\AMZN_puts_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\AMZN_calls_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\AMZN_puts_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\AMZN_calls_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\AMZN_puts_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\AMZN_calls_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\AMZN_puts_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\AMZN_calls_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\AMZN_puts_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\AMZN_calls_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\AMZN_puts_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\AMZN_calls_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\AMZN_puts_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\AMZN_calls_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\AMZN_puts_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\AMZN_calls_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\AMZN_puts_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\AMZN_calls_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\AMZN_puts_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\AMZN_calls_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\AMZN_puts_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\AMZN_calls_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\AMZN_puts_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\AMZN_calls_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\AMZN_puts_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\AMZN_calls_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\AMZN_puts_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\AMZN_calls_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\AMZN_puts_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\AMZN_calls_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\AMZN_puts_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\AMZN_calls_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\AMZN_puts_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\AMZN_calls_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\AMZN_puts_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\AMZN_calls_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\AMZN_puts_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\AMZN_calls_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\AMZN_puts_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\AMZN_calls_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\AMZN_puts_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\AMZN_calls_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\AMZN_puts_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\AMZN_calls_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\AMZN_puts_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\AMZN_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\AMZN_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\AMZN_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\AMZN_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\AMZN_calls_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\AMZN_puts_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\AMZN_calls_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\AMZN_puts_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\AMZN_calls_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\AMZN_puts_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\AMZN_calls_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\AMZN_puts_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\AMZN_calls_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\AMZN_puts_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\AMZN_calls_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\AMZN_puts_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\AMZN_calls_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\AMZN_puts_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\AMZN_calls_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\AMZN_puts_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\AMZN_calls_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\AMZN_puts_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\AMZN_calls_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\AMZN_puts_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\AMZN_calls_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\AMZN_puts_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\AMZN_calls_all_for_2026-01-05.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\AMZN_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (170543, 16)
INFO:utilities:Removed 52698 duplicates
INFO:utilities:174 files found for keyword: googl

['./daily historical datas/Technology\\Tech_sector_2025-09-12\\GOOGL_calls_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-12\\GOOGL_puts_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\GOOGL_calls_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\GOOGL_puts_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\GOOGL_calls_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\GOOGL_puts_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\GOOGL_calls_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\GOOGL_puts_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\GOOGL_calls_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\GOOGL_puts_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\GOOGL_calls_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\GOOGL_puts_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\GOOGL_calls_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\GOOGL_puts_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\GOOGL_calls_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\GOOGL_puts_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\GOOGL_calls_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\GOOGL_puts_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\GOOGL_calls_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\GOOGL_puts_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\GOOGL_calls_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\GOOGL_puts_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\GOOGL_calls_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\GOOGL_puts_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\GOOGL_calls_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\GOOGL_puts_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\GOOGL_calls_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\GOOGL_puts_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\GOOGL_calls_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\GOOGL_puts_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\GOOGL_calls_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\GOOGL_puts_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\GOOGL_calls_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\GOOGL_puts_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\GOOGL_calls_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\GOOGL_puts_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\GOOGL_calls_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\GOOGL_puts_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\GOOGL_calls_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\GOOGL_puts_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\GOOGL_calls_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\GOOGL_puts_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\GOOGL_calls_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\GOOGL_puts_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\GOOGL_calls_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\GOOGL_puts_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\GOOGL_calls_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\GOOGL_puts_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\GOOGL_calls_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\GOOGL_puts_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\GOOGL_calls_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\GOOGL_puts_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\GOOGL_calls_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\GOOGL_puts_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\GOOGL_calls_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\GOOGL_puts_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\GOOGL_calls_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\GOOGL_puts_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\GOOGL_calls_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\GOOGL_puts_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\GOOGL_calls_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\GOOGL_puts_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\GOOGL_calls_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\GOOGL_puts_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\GOOGL_calls_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\GOOGL_puts_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\GOOGL_calls_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\GOOGL_puts_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\GOOGL_calls_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\GOOGL_puts_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\GOOGL_calls_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\GOOGL_puts_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\GOOGL_calls_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\GOOGL_puts_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\GOOGL_calls_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\GOOGL_puts_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\GOOGL_calls_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\GOOGL_puts_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\GOOGL_calls_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\GOOGL_puts_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\GOOGL_calls_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\GOOGL_puts_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\GOOGL_calls_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\GOOGL_puts_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\GOOGL_calls_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\GOOGL_puts_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\GOOGL_calls_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\GOOGL_puts_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\GOOGL_calls_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\GOOGL_puts_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\GOOGL_calls_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\GOOGL_puts_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\GOOGL_calls_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\GOOGL_puts_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\GOOGL_calls_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\GOOGL_puts_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\GOOGL_calls_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\GOOGL_puts_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\GOOGL_calls_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\GOOGL_puts_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\GOOGL_calls_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\GOOGL_puts_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\GOOGL_calls_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\GOOGL_puts_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\GOOGL_calls_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\GOOGL_puts_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\GOOGL_calls_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\GOOGL_puts_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\GOOGL_calls_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\GOOGL_puts_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\GOOGL_calls_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\GOOGL_puts_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\GOOGL_calls_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\GOOGL_puts_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\GOOGL_calls_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\GOOGL_puts_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\GOOGL_calls_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\GOOGL_puts_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\GOOGL_calls_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\GOOGL_puts_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\GOOGL_calls_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\GOOGL_puts_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\GOOGL_calls_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\GOOGL_puts_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\GOOGL_calls_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\GOOGL_puts_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\GOOGL_calls_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\GOOGL_puts_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\GOOGL_calls_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\GOOGL_puts_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\GOOGL_calls_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\GOOGL_puts_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\GOOGL_calls_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\GOOGL_puts_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\GOOGL_calls_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\GOOGL_puts_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\GOOGL_calls_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\GOOGL_puts_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\GOOGL_calls_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\GOOGL_puts_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\GOOGL_calls_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\GOOGL_puts_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\GOOGL_calls_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\GOOGL_puts_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\GOOGL_calls_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\GOOGL_puts_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\GOOGL_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\GOOGL_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\GOOGL_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\GOOGL_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\GOOGL_calls_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\GOOGL_puts_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\GOOGL_calls_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\GOOGL_puts_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\GOOGL_calls_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\GOOGL_puts_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\GOOGL_calls_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\GOOGL_puts_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\GOOGL_calls_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\GOOGL_puts_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\GOOGL_calls_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\GOOGL_puts_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\GOOGL_calls_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\GOOGL_puts_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\GOOGL_calls_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\GOOGL_puts_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\GOOGL_calls_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\GOOGL_puts_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\GOOGL_calls_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\GOOGL_puts_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\GOOGL_calls_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\GOOGL_puts_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\GOOGL_calls_all_for_2026-01-05.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\GOOGL_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (220978, 16)
INFO:utilities:Removed 94565 duplicates
INFO:utilities:174 files found for keyword: meta

['./daily historical datas/Technology\\Tech_sector_2025-09-12\\META_calls_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-12\\META_puts_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\META_calls_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\META_puts_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\META_calls_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\META_puts_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\META_calls_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\META_puts_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\META_calls_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\META_puts_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\META_calls_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\META_puts_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\META_calls_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\META_puts_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\META_calls_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\META_puts_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\META_calls_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\META_puts_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\META_calls_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\META_puts_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\META_calls_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\META_puts_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\META_calls_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\META_puts_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\META_calls_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\META_puts_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\META_calls_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\META_puts_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\META_calls_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\META_puts_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\META_calls_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\META_puts_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\META_calls_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\META_puts_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\META_calls_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\META_puts_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\META_calls_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\META_puts_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\META_calls_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\META_puts_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\META_calls_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\META_puts_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\META_calls_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\META_puts_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\META_calls_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\META_puts_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\META_calls_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\META_puts_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\META_calls_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\META_puts_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\META_calls_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\META_puts_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\META_calls_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\META_puts_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\META_calls_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\META_puts_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\META_calls_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\META_puts_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\META_calls_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\META_puts_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\META_calls_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\META_puts_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\META_calls_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\META_puts_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\META_calls_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\META_puts_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\META_calls_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\META_puts_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\META_calls_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\META_puts_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\META_calls_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\META_puts_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\META_calls_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\META_puts_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\META_calls_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\META_puts_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\META_calls_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\META_puts_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\META_calls_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\META_puts_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\META_calls_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\META_puts_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\META_calls_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\META_puts_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\META_calls_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\META_puts_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\META_calls_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\META_puts_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\META_calls_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\META_puts_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\META_calls_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\META_puts_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\META_calls_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\META_puts_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\META_calls_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\META_puts_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\META_calls_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\META_puts_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\META_calls_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\META_puts_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\META_calls_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\META_puts_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\META_calls_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\META_puts_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\META_calls_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\META_puts_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\META_calls_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\META_puts_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\META_calls_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\META_puts_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\META_calls_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\META_puts_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\META_calls_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\META_puts_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\META_calls_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\META_puts_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\META_calls_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\META_puts_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\META_calls_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\META_puts_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\META_calls_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\META_puts_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\META_calls_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\META_puts_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\META_calls_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\META_puts_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\META_calls_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\META_puts_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\META_calls_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\META_puts_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\META_calls_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\META_puts_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\META_calls_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\META_puts_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\META_calls_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\META_puts_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\META_calls_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\META_puts_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\META_calls_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\META_puts_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\META_calls_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\META_puts_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\META_calls_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\META_puts_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\META_calls_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\META_puts_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\META_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\META_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\META_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\META_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\META_calls_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\META_puts_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\META_calls_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\META_puts_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\META_calls_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\META_puts_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\META_calls_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\META_puts_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\META_calls_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\META_puts_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\META_calls_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\META_puts_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\META_calls_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\META_puts_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\META_calls_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\META_puts_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\META_calls_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\META_puts_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\META_calls_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\META_puts_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\META_calls_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\META_puts_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\META_calls_all_for_2026-01-05.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\META_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (403544, 16)
INFO:utilities:Removed 208241 duplicates
INFO:utilities:174 files found for keyword: msft

['./daily historical datas/Technology\\Tech_sector_2025-09-12\\MSFT_calls_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-12\\MSFT_puts_all_for_2025-09-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\MSFT_calls_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-15\\MSFT_puts_all_for_2025-09-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\MSFT_calls_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-16\\MSFT_puts_all_for_2025-09-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\MSFT_calls_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-17\\MSFT_puts_all_for_2025-09-17.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\MSFT_calls_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-18\\MSFT_puts_all_for_2025-09-18.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\MSFT_calls_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\MSFT_puts_all_for_2025-09-19.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\MSFT_calls_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-06\\MSFT_puts_all_for_2026-01-06.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\MSFT_calls_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-07\\MSFT_puts_all_for_2026-01-07.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\MSFT_calls_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-08\\MSFT_puts_all_for_2026-01-08.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\MSFT_calls_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-09\\MSFT_puts_all_for_2026-01-09.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\MSFT_calls_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-12\\MSFT_puts_all_for_2026-01-12.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\MSFT_calls_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-13\\MSFT_puts_all_for_2026-01-13.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\MSFT_calls_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-14\\MSFT_puts_all_for_2026-01-14.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\MSFT_calls_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-15\\MSFT_puts_all_for_2026-01-15.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\MSFT_calls_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-16\\MSFT_puts_all_for_2026-01-16.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\MSFT_calls_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-19\\Tech_sector_2026-01-20\\MSFT_puts_all_for_2026-01-20.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\MSFT_calls_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-22\\MSFT_puts_all_for_2025-09-22.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\MSFT_calls_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-23\\MSFT_puts_all_for_2025-09-23.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\MSFT_calls_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-24\\MSFT_puts_all_for_2025-09-24.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\MSFT_calls_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-25\\MSFT_puts_all_for_2025-09-25.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\MSFT_calls_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-26\\MSFT_puts_all_for_2025-09-26.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\MSFT_calls_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-29\\MSFT_puts_all_for_2025-09-29.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\MSFT_calls_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-09-30\\MSFT_puts_all_for_2025-09-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\MSFT_calls_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-01\\MSFT_puts_all_for_2025-10-01.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\MSFT_calls_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-02\\MSFT_puts_all_for_2025-10-02.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\MSFT_calls_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-03\\MSFT_puts_all_for_2025-10-03.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\MSFT_calls_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-06\\MSFT_puts_all_for_2025-10-06.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\MSFT_calls_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-07\\MSFT_puts_all_for_2025-10-07.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\MSFT_calls_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-08\\MSFT_puts_all_for_2025-10-08.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\MSFT_calls_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-09\\MSFT_puts_all_for_2025-10-09.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\MSFT_calls_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-10\\MSFT_puts_all_for_2025-10-10.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\MSFT_calls_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-13\\MSFT_puts_all_for_2025-10-13.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\MSFT_calls_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-14\\MSFT_puts_all_for_2025-10-14.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\MSFT_calls_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-15\\MSFT_puts_all_for_2025-10-15.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\MSFT_calls_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-16\\MSFT_puts_all_for_2025-10-16.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\MSFT_calls_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-17\\MSFT_puts_all_for_2025-10-17.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\MSFT_calls_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-19\\MSFT_puts_all_for_2025-10-19.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\MSFT_calls_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-21\\MSFT_puts_all_for_2025-10-21.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\MSFT_calls_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-22\\MSFT_puts_all_for_2025-10-22.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\MSFT_calls_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-23\\MSFT_puts_all_for_2025-10-23.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\MSFT_calls_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-24\\MSFT_puts_all_for_2025-10-24.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\MSFT_calls_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-27\\MSFT_puts_all_for_2025-10-27.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\MSFT_calls_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-28\\MSFT_puts_all_for_2025-10-28.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\MSFT_calls_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-29\\MSFT_puts_all_for_2025-10-29.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\MSFT_calls_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-30\\MSFT_puts_all_for_2025-10-30.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\MSFT_calls_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-10-31\\MSFT_puts_all_for_2025-10-31.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\MSFT_calls_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-03\\MSFT_puts_all_for_2025-11-03.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\MSFT_calls_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-04\\MSFT_puts_all_for_2025-11-04.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\MSFT_calls_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-05\\MSFT_puts_all_for_2025-11-05.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\MSFT_calls_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-06\\MSFT_puts_all_for_2025-11-06.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\MSFT_calls_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-07\\MSFT_puts_all_for_2025-11-07.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\MSFT_calls_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-10\\MSFT_puts_all_for_2025-11-10.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\MSFT_calls_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-11\\MSFT_puts_all_for_2025-11-11.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\MSFT_calls_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-12\\MSFT_puts_all_for_2025-11-12.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\MSFT_calls_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-14\\MSFT_puts_all_for_2025-11-14.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\MSFT_calls_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-17\\MSFT_puts_all_for_2025-11-17.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\MSFT_calls_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-18\\MSFT_puts_all_for_2025-11-18.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\MSFT_calls_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-19\\MSFT_puts_all_for_2025-11-19.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\MSFT_calls_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-20\\MSFT_puts_all_for_2025-11-20.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\MSFT_calls_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-21\\MSFT_puts_all_for_2025-11-21.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\MSFT_calls_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-24\\MSFT_puts_all_for_2025-11-24.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\MSFT_calls_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-25\\MSFT_puts_all_for_2025-11-25.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\MSFT_calls_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-26\\MSFT_puts_all_for_2025-11-26.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\MSFT_calls_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-27\\MSFT_puts_all_for_2025-11-27.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\MSFT_calls_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-11-28\\MSFT_puts_all_for_2025-11-28.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\MSFT_calls_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-01\\MSFT_puts_all_for_2025-12-01.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\MSFT_calls_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-02\\MSFT_puts_all_for_2025-12-02.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\MSFT_calls_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-03\\MSFT_puts_all_for_2025-12-03.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\MSFT_calls_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-04\\MSFT_puts_all_for_2025-12-04.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\MSFT_calls_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-05\\MSFT_puts_all_for_2025-12-05.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\MSFT_calls_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-08\\MSFT_puts_all_for_2025-12-08.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\MSFT_calls_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-10\\MSFT_puts_all_for_2025-12-10.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\MSFT_calls_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-12\\MSFT_puts_all_for_2025-12-12.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\MSFT_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-15\\MSFT_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\MSFT_calls_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-16\\MSFT_puts_all_for_2025-12-16.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\MSFT_calls_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-17\\MSFT_puts_all_for_2025-12-17.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\MSFT_calls_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-18\\MSFT_puts_all_for_2025-12-18.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\MSFT_calls_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-19\\MSFT_puts_all_for_2025-12-19.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\MSFT_calls_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-23\\MSFT_puts_all_for_2025-12-23.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\MSFT_calls_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-25\\MSFT_puts_all_for_2025-12-25.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\MSFT_calls_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-26\\MSFT_puts_all_for_2025-12-26.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\MSFT_calls_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-29\\MSFT_puts_all_for_2025-12-29.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\MSFT_calls_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-30\\MSFT_puts_all_for_2025-12-30.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\MSFT_calls_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2025-12-31\\MSFT_puts_all_for_2025-12-31.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\MSFT_calls_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-01\\MSFT_puts_all_for_2026-01-01.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\MSFT_calls_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-02\\MSFT_puts_all_for_2026-01-02.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\MSFT_calls_all_for_2026-01-05.csv', './daily historical datas/Technology\\Tech_sector_2026-01-05\\MSFT_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (249749, 16)
INFO:utilities:Removed 118892 duplicates

In [7]:
for ticker, OptionsData in Finance.items():
  df_final = fusionner_fichiers(folder, finance, ticker)
  df_final = remove_duplicates(df_final)
  Finance[ticker]= df_final

INFO:utilities:174 files found for keyword: bac

['./daily historical datas/Finance\\Finance_sector_2025-09-12\\BAC_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\BAC_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\BAC_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\BAC_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\BAC_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\BAC_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\BAC_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\BAC_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\BAC_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\BAC_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\BAC_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\BAC_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\BAC_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\BAC_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\BAC_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\BAC_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\BAC_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\BAC_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\BAC_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\BAC_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\BAC_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\BAC_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\BAC_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\BAC_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\BAC_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\BAC_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\BAC_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\BAC_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\BAC_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\BAC_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\BAC_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\BAC_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\BAC_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\BAC_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\BAC_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\BAC_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\BAC_calls_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\BAC_puts_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\BAC_calls_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\BAC_puts_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\BAC_calls_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\BAC_puts_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\BAC_calls_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\BAC_puts_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\BAC_calls_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\BAC_puts_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\BAC_calls_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\BAC_puts_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\BAC_calls_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\BAC_puts_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\BAC_calls_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\BAC_puts_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\BAC_calls_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\BAC_puts_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\BAC_calls_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\BAC_puts_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\BAC_calls_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\BAC_puts_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\BAC_calls_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\BAC_puts_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\BAC_calls_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\BAC_puts_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\BAC_calls_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\BAC_puts_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\BAC_calls_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\BAC_puts_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\BAC_calls_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\BAC_puts_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\BAC_calls_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\BAC_puts_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\BAC_calls_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\BAC_puts_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\BAC_calls_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\BAC_puts_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\BAC_calls_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\BAC_puts_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\BAC_calls_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\BAC_puts_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\BAC_calls_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\BAC_puts_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\BAC_calls_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\BAC_puts_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\BAC_calls_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\BAC_puts_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\BAC_calls_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\BAC_puts_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\BAC_calls_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\BAC_puts_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\BAC_calls_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\BAC_puts_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\BAC_calls_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\BAC_puts_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\BAC_calls_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\BAC_puts_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\BAC_calls_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\BAC_puts_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\BAC_calls_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\BAC_puts_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\BAC_calls_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\BAC_puts_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\BAC_calls_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\BAC_puts_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\BAC_calls_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\BAC_puts_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\BAC_calls_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\BAC_puts_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\BAC_calls_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\BAC_puts_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\BAC_calls_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\BAC_puts_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\BAC_calls_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\BAC_puts_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\BAC_calls_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\BAC_puts_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\BAC_calls_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\BAC_puts_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\BAC_calls_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\BAC_puts_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\BAC_calls_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\BAC_puts_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\BAC_calls_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\BAC_puts_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\BAC_calls_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\BAC_puts_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\BAC_calls_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\BAC_puts_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\BAC_calls_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\BAC_puts_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\BAC_calls_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\BAC_puts_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\BAC_calls_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\BAC_puts_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\BAC_calls_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\BAC_puts_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\BAC_calls_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\BAC_puts_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\BAC_calls_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\BAC_puts_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\BAC_calls_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\BAC_puts_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\BAC_calls_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\BAC_puts_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\BAC_calls_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\BAC_puts_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\BAC_calls_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\BAC_puts_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\BAC_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\BAC_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\BAC_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\BAC_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\BAC_calls_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\BAC_puts_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\BAC_calls_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\BAC_puts_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\BAC_calls_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\BAC_puts_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\BAC_calls_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\BAC_puts_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\BAC_calls_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\BAC_puts_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\BAC_calls_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\BAC_puts_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\BAC_calls_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\BAC_puts_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\BAC_calls_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\BAC_puts_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\BAC_calls_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\BAC_puts_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\BAC_calls_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\BAC_puts_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\BAC_calls_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\BAC_puts_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\BAC_calls_all_for_2026-01-05.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\BAC_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (76153, 16)
INFO:utilities:Removed 34954 duplicates
INFO:utilities:870 files found for keyword: c

['./daily historical datas/Finance\\Finance_sector_2025-09-12\\BAC_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\BAC_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\C_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\C_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\GS_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\GS_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\JPM_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\JPM_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\WFC_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\WFC_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\BAC_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\BAC_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\C_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\C_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\GS_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\GS_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\JPM_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\JPM_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\WFC_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\WFC_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\BAC_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\BAC_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\C_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\C_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\GS_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\GS_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\JPM_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\JPM_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\WFC_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\WFC_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\BAC_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\BAC_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\C_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\C_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\GS_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\GS_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\JPM_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\JPM_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\WFC_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\WFC_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\BAC_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\BAC_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\C_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\C_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\GS_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\GS_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\JPM_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\JPM_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\WFC_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\WFC_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\BAC_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\BAC_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\C_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\C_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\GS_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\GS_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\JPM_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\JPM_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\WFC_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\WFC_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\BAC_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\BAC_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\C_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\C_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\GS_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\GS_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\JPM_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\JPM_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\WFC_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\WFC_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\BAC_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\BAC_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\C_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\C_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\GS_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\GS_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\JPM_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\JPM_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\WFC_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\WFC_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\BAC_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\BAC_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\C_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\C_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\GS_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\GS_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\JPM_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\JPM_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\WFC_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\WFC_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\BAC_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\BAC_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\C_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\C_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\GS_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\GS_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\JPM_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\JPM_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\WFC_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\WFC_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\BAC_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\BAC_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\C_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\C_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\GS_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\GS_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\JPM_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\JPM_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\WFC_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\WFC_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\BAC_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\BAC_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\C_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\C_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\GS_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\GS_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\JPM_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\JPM_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\WFC_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\WFC_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\BAC_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\BAC_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\C_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\C_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\GS_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\GS_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\JPM_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\JPM_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\WFC_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\WFC_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\BAC_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\BAC_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\C_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\C_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\GS_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\GS_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\JPM_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\JPM_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\WFC_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\WFC_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\BAC_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\BAC_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\C_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\C_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\GS_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\GS_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\JPM_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\JPM_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\WFC_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\WFC_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\BAC_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\BAC_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\C_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\C_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\GS_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\GS_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\JPM_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\JPM_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\WFC_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\WFC_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\BAC_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\BAC_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\C_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\C_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\GS_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\GS_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\JPM_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\JPM_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\WFC_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\WFC_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\BAC_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\BAC_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\C_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\C_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\GS_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\GS_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\JPM_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\JPM_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\WFC_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\WFC_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Fi

INFO:utilities:Merged dataset shape: (676095, 16)
INFO:utilities:Removed 401476 duplicates
INFO:utilities:174 files found for keyword: gs

['./daily historical datas/Finance\\Finance_sector_2025-09-12\\GS_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\GS_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\GS_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\GS_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\GS_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\GS_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\GS_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\GS_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\GS_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\GS_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\GS_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\GS_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\GS_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\GS_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\GS_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\GS_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\GS_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\GS_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\GS_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\GS_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\GS_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\GS_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\GS_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\GS_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\GS_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\GS_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\GS_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\GS_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\GS_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\GS_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\GS_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\GS_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\GS_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\GS_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\GS_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\GS_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\GS_calls_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\GS_puts_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\GS_calls_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\GS_puts_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\GS_calls_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\GS_puts_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\GS_calls_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\GS_puts_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\GS_calls_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\GS_puts_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\GS_calls_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\GS_puts_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\GS_calls_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\GS_puts_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\GS_calls_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\GS_puts_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\GS_calls_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\GS_puts_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\GS_calls_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\GS_puts_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\GS_calls_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\GS_puts_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\GS_calls_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\GS_puts_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\GS_calls_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\GS_puts_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\GS_calls_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\GS_puts_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\GS_calls_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\GS_puts_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\GS_calls_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\GS_puts_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\GS_calls_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\GS_puts_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\GS_calls_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\GS_puts_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\GS_calls_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\GS_puts_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\GS_calls_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\GS_puts_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\GS_calls_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\GS_puts_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\GS_calls_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\GS_puts_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\GS_calls_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\GS_puts_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\GS_calls_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\GS_puts_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\GS_calls_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\GS_puts_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\GS_calls_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\GS_puts_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\GS_calls_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\GS_puts_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\GS_calls_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\GS_puts_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\GS_calls_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\GS_puts_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\GS_calls_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\GS_puts_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\GS_calls_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\GS_puts_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\GS_calls_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\GS_puts_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\GS_calls_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\GS_puts_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\GS_calls_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\GS_puts_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\GS_calls_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\GS_puts_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\GS_calls_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\GS_puts_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\GS_calls_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\GS_puts_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\GS_calls_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\GS_puts_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\GS_calls_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\GS_puts_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\GS_calls_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\GS_puts_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\GS_calls_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\GS_puts_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\GS_calls_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\GS_puts_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\GS_calls_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\GS_puts_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\GS_calls_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\GS_puts_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\GS_calls_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\GS_puts_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\GS_calls_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\GS_puts_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\GS_calls_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\GS_puts_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\GS_calls_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\GS_puts_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\GS_calls_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\GS_puts_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\GS_calls_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\GS_puts_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\GS_calls_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\GS_puts_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\GS_calls_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\GS_puts_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\GS_calls_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\GS_puts_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\GS_calls_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\GS_puts_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\GS_calls_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\GS_puts_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\GS_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\GS_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\GS_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\GS_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\GS_calls_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\GS_puts_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\GS_calls_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\GS_puts_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\GS_calls_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\GS_puts_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\GS_calls_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\GS_puts_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\GS_calls_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\GS_puts_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\GS_calls_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\GS_puts_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\GS_calls_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\GS_puts_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\GS_calls_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\GS_puts_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\GS_calls_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\GS_puts_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\GS_calls_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\GS_puts_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\GS_calls_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\GS_puts_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\GS_calls_all_for_2026-01-05.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\GS_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (266679, 16)
INFO:utilities:Removed 174325 duplicates
INFO:utilities:174 files found for keyword: jpm

['./daily historical datas/Finance\\Finance_sector_2025-09-12\\JPM_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\JPM_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\JPM_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\JPM_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\JPM_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\JPM_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\JPM_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\JPM_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\JPM_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\JPM_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\JPM_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\JPM_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\JPM_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\JPM_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\JPM_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\JPM_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\JPM_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\JPM_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\JPM_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\JPM_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\JPM_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\JPM_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\JPM_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\JPM_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\JPM_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\JPM_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\JPM_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\JPM_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\JPM_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\JPM_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\JPM_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\JPM_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\JPM_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\JPM_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\JPM_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\JPM_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\JPM_calls_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\JPM_puts_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\JPM_calls_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\JPM_puts_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\JPM_calls_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\JPM_puts_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\JPM_calls_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\JPM_puts_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\JPM_calls_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\JPM_puts_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\JPM_calls_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\JPM_puts_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\JPM_calls_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\JPM_puts_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\JPM_calls_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\JPM_puts_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\JPM_calls_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\JPM_puts_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\JPM_calls_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\JPM_puts_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\JPM_calls_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\JPM_puts_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\JPM_calls_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\JPM_puts_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\JPM_calls_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\JPM_puts_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\JPM_calls_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\JPM_puts_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\JPM_calls_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\JPM_puts_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\JPM_calls_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\JPM_puts_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\JPM_calls_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\JPM_puts_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\JPM_calls_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\JPM_puts_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\JPM_calls_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\JPM_puts_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\JPM_calls_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\JPM_puts_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\JPM_calls_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\JPM_puts_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\JPM_calls_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\JPM_puts_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\JPM_calls_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\JPM_puts_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\JPM_calls_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\JPM_puts_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\JPM_calls_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\JPM_puts_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\JPM_calls_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\JPM_puts_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\JPM_calls_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\JPM_puts_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\JPM_calls_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\JPM_puts_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\JPM_calls_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\JPM_puts_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\JPM_calls_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\JPM_puts_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\JPM_calls_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\JPM_puts_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\JPM_calls_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\JPM_puts_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\JPM_calls_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\JPM_puts_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\JPM_calls_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\JPM_puts_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\JPM_calls_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\JPM_puts_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\JPM_calls_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\JPM_puts_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\JPM_calls_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\JPM_puts_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\JPM_calls_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\JPM_puts_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\JPM_calls_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\JPM_puts_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\JPM_calls_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\JPM_puts_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\JPM_calls_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\JPM_puts_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\JPM_calls_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\JPM_puts_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\JPM_calls_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\JPM_puts_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\JPM_calls_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\JPM_puts_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\JPM_calls_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\JPM_puts_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\JPM_calls_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\JPM_puts_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\JPM_calls_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\JPM_puts_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\JPM_calls_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\JPM_puts_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\JPM_calls_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\JPM_puts_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\JPM_calls_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\JPM_puts_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\JPM_calls_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\JPM_puts_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\JPM_calls_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\JPM_puts_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\JPM_calls_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\JPM_puts_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\JPM_calls_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\JPM_puts_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\JPM_calls_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\JPM_puts_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\JPM_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\JPM_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\JPM_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\JPM_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\JPM_calls_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\JPM_puts_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\JPM_calls_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\JPM_puts_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\JPM_calls_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\JPM_puts_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\JPM_calls_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\JPM_puts_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\JPM_calls_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\JPM_puts_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\JPM_calls_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\JPM_puts_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\JPM_calls_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\JPM_puts_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\JPM_calls_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\JPM_puts_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\JPM_calls_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\JPM_puts_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\JPM_calls_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\JPM_puts_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\JPM_calls_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\JPM_puts_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\JPM_calls_all_for_2026-01-05.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\JPM_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (143296, 16)
INFO:utilities:Removed 84267 duplicates
INFO:utilities:174 files found for keyword: wfc

['./daily historical datas/Finance\\Finance_sector_2025-09-12\\WFC_calls_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-12\\WFC_puts_all_for_2025-09-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\WFC_calls_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-15\\WFC_puts_all_for_2025-09-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\WFC_calls_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-16\\WFC_puts_all_for_2025-09-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\WFC_calls_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-17\\WFC_puts_all_for_2025-09-17.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\WFC_calls_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-18\\WFC_puts_all_for_2025-09-18.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\WFC_calls_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-19\\WFC_puts_all_for_2025-09-19.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\WFC_calls_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-22\\WFC_puts_all_for_2025-09-22.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\WFC_calls_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\WFC_puts_all_for_2025-09-23.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\WFC_calls_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-06\\WFC_puts_all_for_2026-01-06.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\WFC_calls_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-07\\WFC_puts_all_for_2026-01-07.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\WFC_calls_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-08\\WFC_puts_all_for_2026-01-08.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\WFC_calls_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-09\\WFC_puts_all_for_2026-01-09.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\WFC_calls_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-12\\WFC_puts_all_for_2026-01-12.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\WFC_calls_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-13\\WFC_puts_all_for_2026-01-13.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\WFC_calls_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-14\\WFC_puts_all_for_2026-01-14.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\WFC_calls_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-15\\WFC_puts_all_for_2026-01-15.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\WFC_calls_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-16\\WFC_puts_all_for_2026-01-16.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\WFC_calls_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-23\\Finance_sector_2026-01-20\\WFC_puts_all_for_2026-01-20.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\WFC_calls_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-24\\WFC_puts_all_for_2025-09-24.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\WFC_calls_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-25\\WFC_puts_all_for_2025-09-25.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\WFC_calls_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-26\\WFC_puts_all_for_2025-09-26.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\WFC_calls_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-29\\WFC_puts_all_for_2025-09-29.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\WFC_calls_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-09-30\\WFC_puts_all_for_2025-09-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\WFC_calls_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-01\\WFC_puts_all_for_2025-10-01.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\WFC_calls_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-02\\WFC_puts_all_for_2025-10-02.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\WFC_calls_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-03\\WFC_puts_all_for_2025-10-03.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\WFC_calls_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-06\\WFC_puts_all_for_2025-10-06.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\WFC_calls_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-07\\WFC_puts_all_for_2025-10-07.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\WFC_calls_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-08\\WFC_puts_all_for_2025-10-08.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\WFC_calls_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-09\\WFC_puts_all_for_2025-10-09.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\WFC_calls_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-10\\WFC_puts_all_for_2025-10-10.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\WFC_calls_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-13\\WFC_puts_all_for_2025-10-13.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\WFC_calls_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-14\\WFC_puts_all_for_2025-10-14.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\WFC_calls_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-15\\WFC_puts_all_for_2025-10-15.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\WFC_calls_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-16\\WFC_puts_all_for_2025-10-16.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\WFC_calls_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-17\\WFC_puts_all_for_2025-10-17.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\WFC_calls_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-19\\WFC_puts_all_for_2025-10-19.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\WFC_calls_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-21\\WFC_puts_all_for_2025-10-21.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\WFC_calls_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-22\\WFC_puts_all_for_2025-10-22.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\WFC_calls_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-23\\WFC_puts_all_for_2025-10-23.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\WFC_calls_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-24\\WFC_puts_all_for_2025-10-24.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\WFC_calls_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-27\\WFC_puts_all_for_2025-10-27.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\WFC_calls_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-28\\WFC_puts_all_for_2025-10-28.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\WFC_calls_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-29\\WFC_puts_all_for_2025-10-29.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\WFC_calls_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-30\\WFC_puts_all_for_2025-10-30.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\WFC_calls_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-10-31\\WFC_puts_all_for_2025-10-31.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\WFC_calls_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-03\\WFC_puts_all_for_2025-11-03.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\WFC_calls_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-04\\WFC_puts_all_for_2025-11-04.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\WFC_calls_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-05\\WFC_puts_all_for_2025-11-05.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\WFC_calls_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-06\\WFC_puts_all_for_2025-11-06.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\WFC_calls_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-07\\WFC_puts_all_for_2025-11-07.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\WFC_calls_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-10\\WFC_puts_all_for_2025-11-10.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\WFC_calls_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-11\\WFC_puts_all_for_2025-11-11.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\WFC_calls_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-12\\WFC_puts_all_for_2025-11-12.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\WFC_calls_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-14\\WFC_puts_all_for_2025-11-14.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\WFC_calls_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-17\\WFC_puts_all_for_2025-11-17.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\WFC_calls_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-18\\WFC_puts_all_for_2025-11-18.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\WFC_calls_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-19\\WFC_puts_all_for_2025-11-19.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\WFC_calls_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-20\\WFC_puts_all_for_2025-11-20.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\WFC_calls_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-21\\WFC_puts_all_for_2025-11-21.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\WFC_calls_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-24\\WFC_puts_all_for_2025-11-24.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\WFC_calls_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-25\\WFC_puts_all_for_2025-11-25.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\WFC_calls_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-26\\WFC_puts_all_for_2025-11-26.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\WFC_calls_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-27\\WFC_puts_all_for_2025-11-27.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\WFC_calls_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-11-28\\WFC_puts_all_for_2025-11-28.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\WFC_calls_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-01\\WFC_puts_all_for_2025-12-01.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\WFC_calls_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-02\\WFC_puts_all_for_2025-12-02.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\WFC_calls_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-03\\WFC_puts_all_for_2025-12-03.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\WFC_calls_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-04\\WFC_puts_all_for_2025-12-04.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\WFC_calls_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-05\\WFC_puts_all_for_2025-12-05.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\WFC_calls_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-08\\WFC_puts_all_for_2025-12-08.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\WFC_calls_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-10\\WFC_puts_all_for_2025-12-10.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\WFC_calls_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-12\\WFC_puts_all_for_2025-12-12.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\WFC_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-15\\WFC_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\WFC_calls_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-16\\WFC_puts_all_for_2025-12-16.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\WFC_calls_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-17\\WFC_puts_all_for_2025-12-17.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\WFC_calls_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-18\\WFC_puts_all_for_2025-12-18.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\WFC_calls_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-19\\WFC_puts_all_for_2025-12-19.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\WFC_calls_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-23\\WFC_puts_all_for_2025-12-23.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\WFC_calls_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-25\\WFC_puts_all_for_2025-12-25.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\WFC_calls_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-26\\WFC_puts_all_for_2025-12-26.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\WFC_calls_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-29\\WFC_puts_all_for_2025-12-29.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\WFC_calls_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-30\\WFC_puts_all_for_2025-12-30.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\WFC_calls_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2025-12-31\\WFC_puts_all_for_2025-12-31.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\WFC_calls_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-01\\WFC_puts_all_for_2026-01-01.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\WFC_calls_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-02\\WFC_puts_all_for_2026-01-02.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\WFC_calls_all_for_2026-01-05.csv', './daily historical datas/Finance\\Finance_sector_2026-01-05\\WFC_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (86116, 16)
INFO:utilities:Removed 50233 duplicates

In [8]:
for ticker, OptionsData in Health.items():
  df_final = fusionner_fichiers(folder, health, ticker)
  df_final = remove_duplicates(df_final)
  Health[ticker]= df_final

INFO:utilities:174 files found for keyword: abbv

['./daily historical datas/Healthcare\\Health_sector_2025-09-12\\ABBV_calls_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-12\\ABBV_puts_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\ABBV_calls_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\ABBV_puts_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\ABBV_calls_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\ABBV_puts_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\ABBV_calls_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\ABBV_puts_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\ABBV_calls_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\ABBV_puts_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\ABBV_calls_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\ABBV_puts_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\ABBV_calls_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\ABBV_puts_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\ABBV_calls_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\ABBV_puts_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\ABBV_calls_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\ABBV_puts_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\ABBV_calls_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\ABBV_puts_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\ABBV_calls_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\ABBV_puts_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\ABBV_calls_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\ABBV_puts_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\ABBV_calls_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\ABBV_puts_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\ABBV_calls_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\ABBV_puts_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\ABBV_calls_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\ABBV_puts_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\ABBV_calls_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\ABBV_puts_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\ABBV_calls_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\ABBV_puts_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\ABBV_calls_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\ABBV_puts_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\ABBV_calls_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\ABBV_puts_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\ABBV_calls_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\ABBV_puts_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\ABBV_calls_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\ABBV_puts_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\ABBV_calls_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\ABBV_puts_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\ABBV_calls_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\ABBV_puts_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\ABBV_calls_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\ABBV_puts_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\ABBV_calls_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\ABBV_puts_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\ABBV_calls_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\ABBV_puts_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\ABBV_calls_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\ABBV_puts_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\ABBV_calls_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\ABBV_puts_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\ABBV_calls_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\ABBV_puts_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\ABBV_calls_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\ABBV_puts_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\ABBV_calls_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\ABBV_puts_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\ABBV_calls_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\ABBV_puts_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\ABBV_calls_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\ABBV_puts_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\ABBV_calls_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\ABBV_puts_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\ABBV_calls_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\ABBV_puts_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\ABBV_calls_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\ABBV_puts_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\ABBV_calls_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\ABBV_puts_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\ABBV_calls_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\ABBV_puts_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\ABBV_calls_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\ABBV_puts_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\ABBV_calls_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\ABBV_puts_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\ABBV_calls_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\ABBV_puts_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\ABBV_calls_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\ABBV_puts_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\ABBV_calls_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\ABBV_puts_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\ABBV_calls_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\ABBV_puts_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\ABBV_calls_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\ABBV_puts_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\ABBV_calls_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\ABBV_puts_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\ABBV_calls_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\ABBV_puts_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\ABBV_calls_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\ABBV_puts_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\ABBV_calls_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\ABBV_puts_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\ABBV_calls_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\ABBV_puts_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\ABBV_calls_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\ABBV_puts_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\ABBV_calls_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\ABBV_puts_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\ABBV_calls_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\ABBV_puts_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\ABBV_calls_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\ABBV_puts_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\ABBV_calls_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\ABBV_puts_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\ABBV_calls_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\ABBV_puts_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\ABBV_calls_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\ABBV_puts_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\ABBV_calls_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\ABBV_puts_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\ABBV_calls_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\ABBV_puts_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\ABBV_calls_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\ABBV_puts_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\ABBV_calls_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\ABBV_puts_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\ABBV_calls_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\ABBV_puts_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\ABBV_calls_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\ABBV_puts_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\ABBV_calls_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\ABBV_puts_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\ABBV_calls_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\ABBV_puts_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\ABBV_calls_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\ABBV_puts_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\ABBV_calls_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\ABBV_puts_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\ABBV_calls_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\ABBV_puts_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\ABBV_calls_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\ABBV_puts_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\ABBV_calls_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\ABBV_puts_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\ABBV_calls_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\ABBV_puts_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\ABBV_calls_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\ABBV_puts_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\ABBV_calls_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\ABBV_puts_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\ABBV_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\ABBV_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\ABBV_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\ABBV_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\ABBV_calls_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\ABBV_puts_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\ABBV_calls_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\ABBV_puts_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\ABBV_calls_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\ABBV_puts_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\ABBV_calls_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\ABBV_puts_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\ABBV_calls_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\ABBV_puts_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\ABBV_calls_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\ABBV_puts_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\ABBV_calls_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\ABBV_puts_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\ABBV_calls_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\ABBV_puts_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\ABBV_calls_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\ABBV_puts_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\ABBV_calls_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\ABBV_puts_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\ABBV_calls_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\ABBV_puts_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\ABBV_calls_all_for_2026-01-05.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\ABBV_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (78132, 16)
INFO:utilities:Removed 52811 duplicates
INFO:utilities:174 files found for keyword: jnj

['./daily historical datas/Healthcare\\Health_sector_2025-09-12\\JNJ_calls_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-12\\JNJ_puts_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\JNJ_calls_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\JNJ_puts_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\JNJ_calls_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\JNJ_puts_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\JNJ_calls_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\JNJ_puts_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\JNJ_calls_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\JNJ_puts_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\JNJ_calls_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\JNJ_puts_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\JNJ_calls_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\JNJ_puts_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\JNJ_calls_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\JNJ_puts_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\JNJ_calls_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\JNJ_puts_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\JNJ_calls_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\JNJ_puts_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\JNJ_calls_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\JNJ_puts_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\JNJ_calls_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\JNJ_puts_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\JNJ_calls_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\JNJ_puts_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\JNJ_calls_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\JNJ_puts_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\JNJ_calls_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\JNJ_puts_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\JNJ_calls_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\JNJ_puts_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\JNJ_calls_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\JNJ_puts_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\JNJ_calls_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\JNJ_puts_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\JNJ_calls_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\JNJ_puts_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\JNJ_calls_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\JNJ_puts_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\JNJ_calls_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\JNJ_puts_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\JNJ_calls_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\JNJ_puts_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\JNJ_calls_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\JNJ_puts_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\JNJ_calls_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\JNJ_puts_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\JNJ_calls_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\JNJ_puts_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\JNJ_calls_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\JNJ_puts_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\JNJ_calls_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\JNJ_puts_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\JNJ_calls_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\JNJ_puts_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\JNJ_calls_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\JNJ_puts_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\JNJ_calls_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\JNJ_puts_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\JNJ_calls_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\JNJ_puts_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\JNJ_calls_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\JNJ_puts_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\JNJ_calls_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\JNJ_puts_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\JNJ_calls_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\JNJ_puts_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\JNJ_calls_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\JNJ_puts_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\JNJ_calls_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\JNJ_puts_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\JNJ_calls_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\JNJ_puts_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\JNJ_calls_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\JNJ_puts_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\JNJ_calls_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\JNJ_puts_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\JNJ_calls_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\JNJ_puts_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\JNJ_calls_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\JNJ_puts_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\JNJ_calls_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\JNJ_puts_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\JNJ_calls_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\JNJ_puts_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\JNJ_calls_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\JNJ_puts_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\JNJ_calls_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\JNJ_puts_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\JNJ_calls_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\JNJ_puts_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\JNJ_calls_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\JNJ_puts_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\JNJ_calls_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\JNJ_puts_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\JNJ_calls_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\JNJ_puts_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\JNJ_calls_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\JNJ_puts_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\JNJ_calls_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\JNJ_puts_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\JNJ_calls_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\JNJ_puts_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\JNJ_calls_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\JNJ_puts_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\JNJ_calls_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\JNJ_puts_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\JNJ_calls_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\JNJ_puts_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\JNJ_calls_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\JNJ_puts_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\JNJ_calls_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\JNJ_puts_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\JNJ_calls_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\JNJ_puts_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\JNJ_calls_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\JNJ_puts_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\JNJ_calls_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\JNJ_puts_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\JNJ_calls_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\JNJ_puts_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\JNJ_calls_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\JNJ_puts_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\JNJ_calls_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\JNJ_puts_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\JNJ_calls_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\JNJ_puts_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\JNJ_calls_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\JNJ_puts_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\JNJ_calls_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\JNJ_puts_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\JNJ_calls_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\JNJ_puts_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\JNJ_calls_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\JNJ_puts_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\JNJ_calls_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\JNJ_puts_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\JNJ_calls_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\JNJ_puts_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\JNJ_calls_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\JNJ_puts_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\JNJ_calls_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\JNJ_puts_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\JNJ_calls_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\JNJ_puts_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\JNJ_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\JNJ_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\JNJ_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\JNJ_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\JNJ_calls_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\JNJ_puts_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\JNJ_calls_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\JNJ_puts_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\JNJ_calls_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\JNJ_puts_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\JNJ_calls_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\JNJ_puts_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\JNJ_calls_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\JNJ_puts_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\JNJ_calls_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\JNJ_puts_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\JNJ_calls_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\JNJ_puts_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\JNJ_calls_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\JNJ_puts_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\JNJ_calls_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\JNJ_puts_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\JNJ_calls_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\JNJ_puts_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\JNJ_calls_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\JNJ_puts_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\JNJ_calls_all_for_2026-01-05.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\JNJ_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (67825, 16)
INFO:utilities:Removed 42727 duplicates
INFO:utilities:174 files found for keyword: mrk

['./daily historical datas/Healthcare\\Health_sector_2025-09-12\\MRK_calls_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-12\\MRK_puts_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\MRK_calls_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\MRK_puts_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\MRK_calls_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\MRK_puts_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\MRK_calls_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\MRK_puts_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\MRK_calls_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\MRK_puts_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\MRK_calls_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\MRK_puts_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\MRK_calls_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\MRK_puts_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\MRK_calls_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\MRK_puts_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\MRK_calls_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\MRK_puts_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\MRK_calls_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\MRK_puts_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\MRK_calls_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\MRK_puts_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\MRK_calls_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\MRK_puts_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\MRK_calls_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\MRK_puts_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\MRK_calls_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\MRK_puts_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\MRK_calls_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\MRK_puts_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\MRK_calls_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\MRK_puts_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\MRK_calls_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\MRK_puts_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\MRK_calls_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\MRK_puts_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\MRK_calls_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\MRK_puts_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\MRK_calls_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\MRK_puts_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\MRK_calls_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\MRK_puts_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\MRK_calls_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\MRK_puts_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\MRK_calls_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\MRK_puts_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\MRK_calls_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\MRK_puts_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\MRK_calls_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\MRK_puts_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\MRK_calls_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\MRK_puts_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\MRK_calls_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\MRK_puts_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\MRK_calls_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\MRK_puts_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\MRK_calls_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\MRK_puts_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\MRK_calls_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\MRK_puts_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\MRK_calls_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\MRK_puts_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\MRK_calls_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\MRK_puts_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\MRK_calls_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\MRK_puts_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\MRK_calls_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\MRK_puts_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\MRK_calls_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\MRK_puts_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\MRK_calls_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\MRK_puts_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\MRK_calls_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\MRK_puts_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\MRK_calls_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\MRK_puts_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\MRK_calls_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\MRK_puts_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\MRK_calls_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\MRK_puts_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\MRK_calls_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\MRK_puts_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\MRK_calls_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\MRK_puts_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\MRK_calls_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\MRK_puts_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\MRK_calls_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\MRK_puts_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\MRK_calls_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\MRK_puts_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\MRK_calls_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\MRK_puts_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\MRK_calls_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\MRK_puts_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\MRK_calls_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\MRK_puts_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\MRK_calls_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\MRK_puts_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\MRK_calls_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\MRK_puts_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\MRK_calls_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\MRK_puts_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\MRK_calls_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\MRK_puts_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\MRK_calls_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\MRK_puts_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\MRK_calls_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\MRK_puts_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\MRK_calls_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\MRK_puts_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\MRK_calls_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\MRK_puts_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\MRK_calls_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\MRK_puts_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\MRK_calls_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\MRK_puts_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\MRK_calls_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\MRK_puts_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\MRK_calls_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\MRK_puts_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\MRK_calls_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\MRK_puts_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\MRK_calls_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\MRK_puts_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\MRK_calls_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\MRK_puts_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\MRK_calls_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\MRK_puts_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\MRK_calls_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\MRK_puts_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\MRK_calls_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\MRK_puts_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\MRK_calls_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\MRK_puts_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\MRK_calls_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\MRK_puts_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\MRK_calls_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\MRK_puts_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\MRK_calls_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\MRK_puts_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\MRK_calls_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\MRK_puts_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\MRK_calls_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\MRK_puts_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\MRK_calls_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\MRK_puts_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\MRK_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\MRK_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\MRK_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\MRK_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\MRK_calls_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\MRK_puts_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\MRK_calls_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\MRK_puts_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\MRK_calls_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\MRK_puts_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\MRK_calls_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\MRK_puts_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\MRK_calls_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\MRK_puts_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\MRK_calls_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\MRK_puts_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\MRK_calls_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\MRK_puts_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\MRK_calls_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\MRK_puts_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\MRK_calls_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\MRK_puts_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\MRK_calls_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\MRK_puts_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\MRK_calls_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\MRK_puts_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\MRK_calls_all_for_2026-01-05.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\MRK_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (71521, 16)
INFO:utilities:Removed 37810 duplicates
INFO:utilities:174 files found for keyword: pfe

['./daily historical datas/Healthcare\\Health_sector_2025-09-12\\PFE_calls_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-12\\PFE_puts_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\PFE_calls_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\PFE_puts_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\PFE_calls_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\PFE_puts_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\PFE_calls_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\PFE_puts_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\PFE_calls_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\PFE_puts_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\PFE_calls_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\PFE_puts_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\PFE_calls_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\PFE_puts_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\PFE_calls_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\PFE_puts_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\PFE_calls_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\PFE_puts_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\PFE_calls_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\PFE_puts_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\PFE_calls_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\PFE_puts_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\PFE_calls_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\PFE_puts_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\PFE_calls_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\PFE_puts_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\PFE_calls_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\PFE_puts_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\PFE_calls_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\PFE_puts_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\PFE_calls_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\PFE_puts_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\PFE_calls_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\PFE_puts_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\PFE_calls_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\PFE_puts_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\PFE_calls_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\PFE_puts_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\PFE_calls_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\PFE_puts_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\PFE_calls_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\PFE_puts_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\PFE_calls_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\PFE_puts_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\PFE_calls_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\PFE_puts_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\PFE_calls_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\PFE_puts_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\PFE_calls_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\PFE_puts_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\PFE_calls_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\PFE_puts_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\PFE_calls_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\PFE_puts_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\PFE_calls_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\PFE_puts_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\PFE_calls_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\PFE_puts_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\PFE_calls_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\PFE_puts_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\PFE_calls_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\PFE_puts_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\PFE_calls_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\PFE_puts_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\PFE_calls_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\PFE_puts_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\PFE_calls_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\PFE_puts_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\PFE_calls_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\PFE_puts_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\PFE_calls_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\PFE_puts_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\PFE_calls_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\PFE_puts_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\PFE_calls_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\PFE_puts_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\PFE_calls_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\PFE_puts_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\PFE_calls_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\PFE_puts_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\PFE_calls_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\PFE_puts_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\PFE_calls_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\PFE_puts_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\PFE_calls_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\PFE_puts_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\PFE_calls_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\PFE_puts_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\PFE_calls_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\PFE_puts_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\PFE_calls_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\PFE_puts_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\PFE_calls_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\PFE_puts_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\PFE_calls_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\PFE_puts_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\PFE_calls_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\PFE_puts_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\PFE_calls_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\PFE_puts_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\PFE_calls_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\PFE_puts_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\PFE_calls_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\PFE_puts_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\PFE_calls_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\PFE_puts_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\PFE_calls_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\PFE_puts_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\PFE_calls_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\PFE_puts_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\PFE_calls_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\PFE_puts_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\PFE_calls_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\PFE_puts_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\PFE_calls_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\PFE_puts_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\PFE_calls_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\PFE_puts_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\PFE_calls_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\PFE_puts_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\PFE_calls_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\PFE_puts_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\PFE_calls_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\PFE_puts_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\PFE_calls_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\PFE_puts_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\PFE_calls_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\PFE_puts_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\PFE_calls_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\PFE_puts_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\PFE_calls_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\PFE_puts_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\PFE_calls_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\PFE_puts_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\PFE_calls_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\PFE_puts_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\PFE_calls_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\PFE_puts_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\PFE_calls_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\PFE_puts_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\PFE_calls_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\PFE_puts_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\PFE_calls_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\PFE_puts_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\PFE_calls_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\PFE_puts_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\PFE_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\PFE_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\PFE_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\PFE_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\PFE_calls_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\PFE_puts_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\PFE_calls_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\PFE_puts_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\PFE_calls_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\PFE_puts_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\PFE_calls_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\PFE_puts_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\PFE_calls_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\PFE_puts_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\PFE_calls_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\PFE_puts_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\PFE_calls_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\PFE_puts_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\PFE_calls_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\PFE_puts_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\PFE_calls_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\PFE_puts_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\PFE_calls_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\PFE_puts_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\PFE_calls_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\PFE_puts_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\PFE_calls_all_for_2026-01-05.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\PFE_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (51543, 16)
INFO:utilities:Removed 21555 duplicates
INFO:utilities:174 files found for keyword: unh

['./daily historical datas/Healthcare\\Health_sector_2025-09-12\\UNH_calls_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-12\\UNH_puts_all_for_2025-09-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\UNH_calls_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-15\\UNH_puts_all_for_2025-09-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\UNH_calls_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-16\\UNH_puts_all_for_2025-09-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\UNH_calls_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-17\\UNH_puts_all_for_2025-09-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\UNH_calls_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-18\\UNH_puts_all_for_2025-09-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\UNH_calls_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\UNH_puts_all_for_2025-09-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\UNH_calls_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-06\\UNH_puts_all_for_2026-01-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\UNH_calls_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-07\\UNH_puts_all_for_2026-01-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\UNH_calls_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-08\\UNH_puts_all_for_2026-01-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\UNH_calls_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-09\\UNH_puts_all_for_2026-01-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\UNH_calls_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-12\\UNH_puts_all_for_2026-01-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\UNH_calls_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-13\\UNH_puts_all_for_2026-01-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\UNH_calls_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-14\\UNH_puts_all_for_2026-01-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\UNH_calls_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-15\\UNH_puts_all_for_2026-01-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\UNH_calls_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-16\\UNH_puts_all_for_2026-01-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\UNH_calls_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-19\\Health_sector_2026-01-20\\UNH_puts_all_for_2026-01-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\UNH_calls_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-22\\UNH_puts_all_for_2025-09-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\UNH_calls_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-23\\UNH_puts_all_for_2025-09-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\UNH_calls_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-24\\UNH_puts_all_for_2025-09-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\UNH_calls_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-25\\UNH_puts_all_for_2025-09-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\UNH_calls_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-26\\UNH_puts_all_for_2025-09-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\UNH_calls_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-29\\UNH_puts_all_for_2025-09-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\UNH_calls_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-09-30\\UNH_puts_all_for_2025-09-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\UNH_calls_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-01\\UNH_puts_all_for_2025-10-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\UNH_calls_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-02\\UNH_puts_all_for_2025-10-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\UNH_calls_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-03\\UNH_puts_all_for_2025-10-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\UNH_calls_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-06\\UNH_puts_all_for_2025-10-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\UNH_calls_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-07\\UNH_puts_all_for_2025-10-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\UNH_calls_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-08\\UNH_puts_all_for_2025-10-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\UNH_calls_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-09\\UNH_puts_all_for_2025-10-09.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\UNH_calls_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-10\\UNH_puts_all_for_2025-10-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\UNH_calls_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-13\\UNH_puts_all_for_2025-10-13.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\UNH_calls_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-14\\UNH_puts_all_for_2025-10-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\UNH_calls_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-15\\UNH_puts_all_for_2025-10-15.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\UNH_calls_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-16\\UNH_puts_all_for_2025-10-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\UNH_calls_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-17\\UNH_puts_all_for_2025-10-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\UNH_calls_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-19\\UNH_puts_all_for_2025-10-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\UNH_calls_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-21\\UNH_puts_all_for_2025-10-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\UNH_calls_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-22\\UNH_puts_all_for_2025-10-22.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\UNH_calls_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-23\\UNH_puts_all_for_2025-10-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\UNH_calls_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-24\\UNH_puts_all_for_2025-10-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\UNH_calls_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-27\\UNH_puts_all_for_2025-10-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\UNH_calls_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-28\\UNH_puts_all_for_2025-10-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\UNH_calls_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-29\\UNH_puts_all_for_2025-10-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\UNH_calls_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-30\\UNH_puts_all_for_2025-10-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\UNH_calls_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-10-31\\UNH_puts_all_for_2025-10-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\UNH_calls_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-03\\UNH_puts_all_for_2025-11-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\UNH_calls_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-04\\UNH_puts_all_for_2025-11-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\UNH_calls_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-05\\UNH_puts_all_for_2025-11-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\UNH_calls_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-06\\UNH_puts_all_for_2025-11-06.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\UNH_calls_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-07\\UNH_puts_all_for_2025-11-07.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\UNH_calls_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-10\\UNH_puts_all_for_2025-11-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\UNH_calls_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-11\\UNH_puts_all_for_2025-11-11.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\UNH_calls_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-12\\UNH_puts_all_for_2025-11-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\UNH_calls_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-14\\UNH_puts_all_for_2025-11-14.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\UNH_calls_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-17\\UNH_puts_all_for_2025-11-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\UNH_calls_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-18\\UNH_puts_all_for_2025-11-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\UNH_calls_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-19\\UNH_puts_all_for_2025-11-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\UNH_calls_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-20\\UNH_puts_all_for_2025-11-20.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\UNH_calls_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-21\\UNH_puts_all_for_2025-11-21.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\UNH_calls_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-24\\UNH_puts_all_for_2025-11-24.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\UNH_calls_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-25\\UNH_puts_all_for_2025-11-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\UNH_calls_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-26\\UNH_puts_all_for_2025-11-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\UNH_calls_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-27\\UNH_puts_all_for_2025-11-27.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\UNH_calls_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-11-28\\UNH_puts_all_for_2025-11-28.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\UNH_calls_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-01\\UNH_puts_all_for_2025-12-01.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\UNH_calls_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-02\\UNH_puts_all_for_2025-12-02.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\UNH_calls_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-03\\UNH_puts_all_for_2025-12-03.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\UNH_calls_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-04\\UNH_puts_all_for_2025-12-04.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\UNH_calls_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-05\\UNH_puts_all_for_2025-12-05.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\UNH_calls_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-08\\UNH_puts_all_for_2025-12-08.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\UNH_calls_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-10\\UNH_puts_all_for_2025-12-10.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\UNH_calls_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-12\\UNH_puts_all_for_2025-12-12.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\UNH_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-15\\UNH_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\UNH_calls_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-16\\UNH_puts_all_for_2025-12-16.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\UNH_calls_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-17\\UNH_puts_all_for_2025-12-17.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\UNH_calls_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-18\\UNH_puts_all_for_2025-12-18.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\UNH_calls_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-19\\UNH_puts_all_for_2025-12-19.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\UNH_calls_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-23\\UNH_puts_all_for_2025-12-23.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\UNH_calls_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-25\\UNH_puts_all_for_2025-12-25.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\UNH_calls_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-26\\UNH_puts_all_for_2025-12-26.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\UNH_calls_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-29\\UNH_puts_all_for_2025-12-29.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\UNH_calls_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-30\\UNH_puts_all_for_2025-12-30.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\UNH_calls_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2025-12-31\\UNH_puts_all_for_2025-12-31.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\UNH_calls_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-01\\UNH_puts_all_for_2026-01-01.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\UNH_calls_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-02\\UNH_puts_all_for_2026-01-02.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\UNH_calls_all_for_2026-01-05.csv', './daily historical datas/Healthcare\\Health_sector_2026-01-05\\UNH_puts_all_for_2026-01-05.csv']

INFO:utilities:Merged dataset shape: (188340, 16)
INFO:utilities:Removed 95158 duplicates

In [9]:
for ticker, OptionsData in Automobile.items():
  df_final = fusionner_fichiers(folder, automobile, ticker)
  df_final = remove_duplicates(df_final)
  Automobile[ticker]= df_final

INFO:utilities:870 files found for keyword: f

['./daily historical datas/Automobile\\Auto_sector_2025-09-12\\F_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\F_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\GM_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\GM_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\LCID_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\LCID_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\RIVN_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\RIVN_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\TSLA_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\TSLA_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\F_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\F_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\GM_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\GM_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\LCID_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\LCID_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\RIVN_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\RIVN_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\TSLA_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\TSLA_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\F_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\F_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\GM_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\GM_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\LCID_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\LCID_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\RIVN_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\RIVN_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\TSLA_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\TSLA_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\F_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\F_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\GM_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\GM_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\LCID_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\LCID_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\RIVN_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\RIVN_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\TSLA_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\TSLA_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\F_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\F_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\GM_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\GM_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\LCID_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\LCID_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\RIVN_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\RIVN_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\TSLA_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\TSLA_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\F_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\F_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\GM_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\GM_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\LCID_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\LCID_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\RIVN_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\RIVN_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\TSLA_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\TSLA_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\F_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\F_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\GM_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\GM_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\LCID_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\LCID_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\RIVN_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\RIVN_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\TSLA_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\TSLA_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\F_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\F_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\GM_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\GM_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\LCID_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\LCID_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\RIVN_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\RIVN_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\TSLA_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\TSLA_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\F_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\F_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\GM_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\GM_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\LCID_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\LCID_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\RIVN_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\RIVN_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\TSLA_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\TSLA_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\F_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\F_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\GM_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\GM_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\LCID_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\LCID_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\RIVN_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\RIVN_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\TSLA_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\TSLA_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\F_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\F_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\GM_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\GM_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\LCID_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\LCID_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\RIVN_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\RIVN_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\TSLA_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\TSLA_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\F_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\F_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\GM_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\GM_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\LCID_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\LCID_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\RIVN_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\RIVN_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\TSLA_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\TSLA_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\F_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\F_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\GM_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\GM_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\LCID_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\LCID_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\RIVN_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\RIVN_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\TSLA_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\TSLA_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\F_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\F_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\GM_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\GM_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\LCID_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\LCID_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\RIVN_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\RIVN_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\TSLA_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\TSLA_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\F_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\F_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\GM_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\GM_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\LCID_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\LCID_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\RIVN_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\RIVN_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\TSLA_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\TSLA_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\F_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\F_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\GM_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\GM_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\LCID_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\LCID_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\RIVN_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\RIVN_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\TSLA_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\TSLA_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\F_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\F_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\GM_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\GM_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\LCID_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\LCID_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\RIVN_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\RIVN_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\TSLA_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\TSLA_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\F_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\F_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\GM_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\GM_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\LCID_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\LCID_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\RIVN_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\RIVN_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\TSLA_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\TSLA_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\F_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\F_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\GM_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\GM_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\LCID_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\LCID_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\RIVN_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\RIVN_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\TSLA_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\TSLA_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\F_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\F_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\GM_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\GM_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\LCID_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\LCID_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\RIVN_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\RIVN_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\TSLA_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\TSLA_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\F_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\F_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\GM_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\GM_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\LCID_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\LCID_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\RIVN_calls_all_for_2025-10-10.csv', './daily historical datas/

INFO:utilities:Merged dataset shape: (662613, 16)
INFO:utilities:Removed 287892 duplicates
INFO:utilities:174 files found for keyword: gm

['./daily historical datas/Automobile\\Auto_sector_2025-09-12\\GM_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\GM_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\GM_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\GM_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\GM_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\GM_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\GM_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\GM_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\GM_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\GM_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\GM_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\GM_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\GM_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\GM_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\GM_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\GM_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\GM_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\GM_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\GM_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\GM_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\GM_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\GM_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\GM_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\GM_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\GM_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\GM_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\GM_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\GM_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\GM_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\GM_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\GM_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\GM_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\GM_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\GM_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\GM_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\GM_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\GM_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\GM_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\GM_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\GM_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\GM_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\GM_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\GM_calls_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\GM_puts_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\GM_calls_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\GM_puts_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\GM_calls_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\GM_puts_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\GM_calls_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\GM_puts_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\GM_calls_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\GM_puts_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\GM_calls_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\GM_puts_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\GM_calls_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\GM_puts_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\GM_calls_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\GM_puts_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\GM_calls_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\GM_puts_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\GM_calls_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\GM_puts_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\GM_calls_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\GM_puts_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\GM_calls_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\GM_puts_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\GM_calls_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\GM_puts_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\GM_calls_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\GM_puts_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\GM_calls_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\GM_puts_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\GM_calls_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\GM_puts_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\GM_calls_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\GM_puts_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\GM_calls_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\GM_puts_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\GM_calls_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\GM_puts_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\GM_calls_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\GM_puts_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\GM_calls_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\GM_puts_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\GM_calls_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\GM_puts_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\GM_calls_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\GM_puts_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\GM_calls_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\GM_puts_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\GM_calls_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\GM_puts_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\GM_calls_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\GM_puts_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\GM_calls_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\GM_puts_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\GM_calls_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\GM_puts_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\GM_calls_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\GM_puts_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\GM_calls_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\GM_puts_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\GM_calls_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\GM_puts_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\GM_calls_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\GM_puts_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\GM_calls_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\GM_puts_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\GM_calls_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\GM_puts_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\GM_calls_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\GM_puts_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\GM_calls_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\GM_puts_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\GM_calls_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\GM_puts_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\GM_calls_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\GM_puts_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\GM_calls_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\GM_puts_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\GM_calls_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\GM_puts_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\GM_calls_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\GM_puts_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\GM_calls_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\GM_puts_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\GM_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\GM_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\GM_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\GM_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\GM_calls_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\GM_puts_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\GM_calls_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\GM_puts_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\GM_calls_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\GM_puts_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\GM_calls_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\GM_puts_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\GM_calls_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\GM_puts_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\GM_calls_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\GM_puts_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\GM_calls_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\GM_puts_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\GM_calls_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\GM_puts_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\GM_calls_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\GM_puts_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\GM_calls_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\GM_puts_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\GM_calls_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\GM_puts_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\GM_calls_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\GM_puts_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\GM_calls_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\GM_puts_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\GM_calls_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\GM_puts_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\GM_calls_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\GM_puts_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\GM_calls_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\GM_puts_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\GM_calls_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\GM_puts_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\GM_calls_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\GM_puts_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\GM_calls_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\GM_puts_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\GM_calls_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\GM_puts_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\GM_calls_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\GM_puts_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\GM_calls_all_for_2026-01-20.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\GM_puts_all_for_2026-01-20.csv']

INFO:utilities:Merged dataset shape: (58129, 16)
INFO:utilities:Removed 32786 duplicates
INFO:utilities:174 files found for keyword: lcid

['./daily historical datas/Automobile\\Auto_sector_2025-09-12\\LCID_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\LCID_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\LCID_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\LCID_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\LCID_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\LCID_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\LCID_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\LCID_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\LCID_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\LCID_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\LCID_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\LCID_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\LCID_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\LCID_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\LCID_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\LCID_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\LCID_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\LCID_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\LCID_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\LCID_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\LCID_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\LCID_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\LCID_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\LCID_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\LCID_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\LCID_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\LCID_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\LCID_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\LCID_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\LCID_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\LCID_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\LCID_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\LCID_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\LCID_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\LCID_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\LCID_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\LCID_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\LCID_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\LCID_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\LCID_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\LCID_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\LCID_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\LCID_calls_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\LCID_puts_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\LCID_calls_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\LCID_puts_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\LCID_calls_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\LCID_puts_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\LCID_calls_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\LCID_puts_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\LCID_calls_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\LCID_puts_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\LCID_calls_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\LCID_puts_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\LCID_calls_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\LCID_puts_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\LCID_calls_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\LCID_puts_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\LCID_calls_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\LCID_puts_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\LCID_calls_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\LCID_puts_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\LCID_calls_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\LCID_puts_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\LCID_calls_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\LCID_puts_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\LCID_calls_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\LCID_puts_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\LCID_calls_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\LCID_puts_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\LCID_calls_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\LCID_puts_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\LCID_calls_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\LCID_puts_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\LCID_calls_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\LCID_puts_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\LCID_calls_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\LCID_puts_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\LCID_calls_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\LCID_puts_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\LCID_calls_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\LCID_puts_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\LCID_calls_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\LCID_puts_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\LCID_calls_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\LCID_puts_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\LCID_calls_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\LCID_puts_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\LCID_calls_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\LCID_puts_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\LCID_calls_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\LCID_puts_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\LCID_calls_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\LCID_puts_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\LCID_calls_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\LCID_puts_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\LCID_calls_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\LCID_puts_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\LCID_calls_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\LCID_puts_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\LCID_calls_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\LCID_puts_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\LCID_calls_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\LCID_puts_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\LCID_calls_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\LCID_puts_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\LCID_calls_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\LCID_puts_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\LCID_calls_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\LCID_puts_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\LCID_calls_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\LCID_puts_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\LCID_calls_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\LCID_puts_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\LCID_calls_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\LCID_puts_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\LCID_calls_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\LCID_puts_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\LCID_calls_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\LCID_puts_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\LCID_calls_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\LCID_puts_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\LCID_calls_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\LCID_puts_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\LCID_calls_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\LCID_puts_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\LCID_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\LCID_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\LCID_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\LCID_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\LCID_calls_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\LCID_puts_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\LCID_calls_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\LCID_puts_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\LCID_calls_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\LCID_puts_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\LCID_calls_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\LCID_puts_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\LCID_calls_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\LCID_puts_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\LCID_calls_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\LCID_puts_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\LCID_calls_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\LCID_puts_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\LCID_calls_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\LCID_puts_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\LCID_calls_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\LCID_puts_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\LCID_calls_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\LCID_puts_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\LCID_calls_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\LCID_puts_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\LCID_calls_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\LCID_puts_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\LCID_calls_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\LCID_puts_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\LCID_calls_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\LCID_puts_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\LCID_calls_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\LCID_puts_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\LCID_calls_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\LCID_puts_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\LCID_calls_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\LCID_puts_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\LCID_calls_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\LCID_puts_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\LCID_calls_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\LCID_puts_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\LCID_calls_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\LCID_puts_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\LCID_calls_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\LCID_puts_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\LCID_calls_all_for_2026-01-20.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\LCID_puts_all_for_2026-01-20.csv']

INFO:utilities:Merged dataset shape: (67711, 16)
INFO:utilities:Removed 43852 duplicates
INFO:utilities:174 files found for keyword: rivn

['./daily historical datas/Automobile\\Auto_sector_2025-09-12\\RIVN_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\RIVN_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\RIVN_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\RIVN_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\RIVN_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\RIVN_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\RIVN_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\RIVN_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\RIVN_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\RIVN_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\RIVN_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\RIVN_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\RIVN_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\RIVN_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\RIVN_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\RIVN_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\RIVN_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\RIVN_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\RIVN_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\RIVN_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\RIVN_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\RIVN_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\RIVN_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\RIVN_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\RIVN_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\RIVN_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\RIVN_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\RIVN_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\RIVN_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\RIVN_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\RIVN_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\RIVN_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\RIVN_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\RIVN_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\RIVN_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\RIVN_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\RIVN_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\RIVN_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\RIVN_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\RIVN_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\RIVN_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\RIVN_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\RIVN_calls_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\RIVN_puts_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\RIVN_calls_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\RIVN_puts_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\RIVN_calls_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\RIVN_puts_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\RIVN_calls_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\RIVN_puts_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\RIVN_calls_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\RIVN_puts_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\RIVN_calls_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\RIVN_puts_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\RIVN_calls_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\RIVN_puts_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\RIVN_calls_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\RIVN_puts_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\RIVN_calls_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\RIVN_puts_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\RIVN_calls_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\RIVN_puts_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\RIVN_calls_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\RIVN_puts_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\RIVN_calls_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\RIVN_puts_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\RIVN_calls_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\RIVN_puts_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\RIVN_calls_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\RIVN_puts_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\RIVN_calls_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\RIVN_puts_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\RIVN_calls_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\RIVN_puts_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\RIVN_calls_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\RIVN_puts_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\RIVN_calls_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\RIVN_puts_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\RIVN_calls_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\RIVN_puts_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\RIVN_calls_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\RIVN_puts_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\RIVN_calls_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\RIVN_puts_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\RIVN_calls_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\RIVN_puts_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\RIVN_calls_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\RIVN_puts_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\RIVN_calls_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\RIVN_puts_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\RIVN_calls_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\RIVN_puts_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\RIVN_calls_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\RIVN_puts_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\RIVN_calls_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\RIVN_puts_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\RIVN_calls_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\RIVN_puts_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\RIVN_calls_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\RIVN_puts_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\RIVN_calls_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\RIVN_puts_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\RIVN_calls_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\RIVN_puts_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\RIVN_calls_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\RIVN_puts_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\RIVN_calls_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\RIVN_puts_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\RIVN_calls_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\RIVN_puts_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\RIVN_calls_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\RIVN_puts_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\RIVN_calls_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\RIVN_puts_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\RIVN_calls_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\RIVN_puts_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\RIVN_calls_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\RIVN_puts_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\RIVN_calls_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\RIVN_puts_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\RIVN_calls_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\RIVN_puts_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\RIVN_calls_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\RIVN_puts_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\RIVN_calls_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\RIVN_puts_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\RIVN_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\RIVN_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\RIVN_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\RIVN_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\RIVN_calls_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\RIVN_puts_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\RIVN_calls_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\RIVN_puts_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\RIVN_calls_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\RIVN_puts_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\RIVN_calls_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\RIVN_puts_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\RIVN_calls_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\RIVN_puts_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\RIVN_calls_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\RIVN_puts_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\RIVN_calls_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\RIVN_puts_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\RIVN_calls_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\RIVN_puts_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\RIVN_calls_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\RIVN_puts_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\RIVN_calls_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\RIVN_puts_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\RIVN_calls_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\RIVN_puts_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\RIVN_calls_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\RIVN_puts_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\RIVN_calls_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\RIVN_puts_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\RIVN_calls_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\RIVN_puts_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\RIVN_calls_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\RIVN_puts_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\RIVN_calls_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\RIVN_puts_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\RIVN_calls_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\RIVN_puts_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\RIVN_calls_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\RIVN_puts_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\RIVN_calls_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\RIVN_puts_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\RIVN_calls_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\RIVN_puts_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\RIVN_calls_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\RIVN_puts_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\RIVN_calls_all_for_2026-01-20.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\RIVN_puts_all_for_2026-01-20.csv']

INFO:utilities:Merged dataset shape: (62692, 16)
INFO:utilities:Removed 25381 duplicates
INFO:utilities:174 files found for keyword: tsla

['./daily historical datas/Automobile\\Auto_sector_2025-09-12\\TSLA_calls_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-12\\TSLA_puts_all_for_2025-09-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\TSLA_calls_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-15\\TSLA_puts_all_for_2025-09-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\TSLA_calls_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-16\\TSLA_puts_all_for_2025-09-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\TSLA_calls_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-17\\TSLA_puts_all_for_2025-09-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\TSLA_calls_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-18\\TSLA_puts_all_for_2025-09-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\TSLA_calls_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-19\\TSLA_puts_all_for_2025-09-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\TSLA_calls_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-22\\TSLA_puts_all_for_2025-09-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\TSLA_calls_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-23\\TSLA_puts_all_for_2025-09-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\TSLA_calls_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-24\\TSLA_puts_all_for_2025-09-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\TSLA_calls_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-25\\TSLA_puts_all_for_2025-09-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\TSLA_calls_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-26\\TSLA_puts_all_for_2025-09-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\TSLA_calls_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-29\\TSLA_puts_all_for_2025-09-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\TSLA_calls_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-09-30\\TSLA_puts_all_for_2025-09-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\TSLA_calls_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-01\\TSLA_puts_all_for_2025-10-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\TSLA_calls_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-02\\TSLA_puts_all_for_2025-10-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\TSLA_calls_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-03\\TSLA_puts_all_for_2025-10-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\TSLA_calls_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-06\\TSLA_puts_all_for_2025-10-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\TSLA_calls_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-07\\TSLA_puts_all_for_2025-10-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\TSLA_calls_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-08\\TSLA_puts_all_for_2025-10-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\TSLA_calls_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-09\\TSLA_puts_all_for_2025-10-09.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\TSLA_calls_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-10\\TSLA_puts_all_for_2025-10-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\TSLA_calls_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-13\\TSLA_puts_all_for_2025-10-13.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\TSLA_calls_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-14\\TSLA_puts_all_for_2025-10-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\TSLA_calls_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-15\\TSLA_puts_all_for_2025-10-15.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\TSLA_calls_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-16\\TSLA_puts_all_for_2025-10-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\TSLA_calls_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-17\\TSLA_puts_all_for_2025-10-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\TSLA_calls_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-19\\TSLA_puts_all_for_2025-10-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\TSLA_calls_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-21\\TSLA_puts_all_for_2025-10-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\TSLA_calls_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-22\\TSLA_puts_all_for_2025-10-22.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\TSLA_calls_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-23\\TSLA_puts_all_for_2025-10-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\TSLA_calls_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-24\\TSLA_puts_all_for_2025-10-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\TSLA_calls_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-27\\TSLA_puts_all_for_2025-10-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\TSLA_calls_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-28\\TSLA_puts_all_for_2025-10-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\TSLA_calls_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-29\\TSLA_puts_all_for_2025-10-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\TSLA_calls_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-30\\TSLA_puts_all_for_2025-10-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\TSLA_calls_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-10-31\\TSLA_puts_all_for_2025-10-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\TSLA_calls_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-03\\TSLA_puts_all_for_2025-11-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\TSLA_calls_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-04\\TSLA_puts_all_for_2025-11-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\TSLA_calls_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-05\\TSLA_puts_all_for_2025-11-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\TSLA_calls_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-06\\TSLA_puts_all_for_2025-11-06.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\TSLA_calls_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-07\\TSLA_puts_all_for_2025-11-07.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\TSLA_calls_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-10\\TSLA_puts_all_for_2025-11-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\TSLA_calls_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-11\\TSLA_puts_all_for_2025-11-11.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\TSLA_calls_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-12\\TSLA_puts_all_for_2025-11-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\TSLA_calls_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-14\\TSLA_puts_all_for_2025-11-14.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\TSLA_calls_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-17\\TSLA_puts_all_for_2025-11-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\TSLA_calls_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-18\\TSLA_puts_all_for_2025-11-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\TSLA_calls_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-19\\TSLA_puts_all_for_2025-11-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\TSLA_calls_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-20\\TSLA_puts_all_for_2025-11-20.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\TSLA_calls_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-21\\TSLA_puts_all_for_2025-11-21.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\TSLA_calls_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-24\\TSLA_puts_all_for_2025-11-24.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\TSLA_calls_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-25\\TSLA_puts_all_for_2025-11-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\TSLA_calls_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-26\\TSLA_puts_all_for_2025-11-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\TSLA_calls_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-27\\TSLA_puts_all_for_2025-11-27.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\TSLA_calls_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-11-28\\TSLA_puts_all_for_2025-11-28.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\TSLA_calls_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-01\\TSLA_puts_all_for_2025-12-01.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\TSLA_calls_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-02\\TSLA_puts_all_for_2025-12-02.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\TSLA_calls_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-03\\TSLA_puts_all_for_2025-12-03.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\TSLA_calls_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-04\\TSLA_puts_all_for_2025-12-04.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\TSLA_calls_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-05\\TSLA_puts_all_for_2025-12-05.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\TSLA_calls_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-08\\TSLA_puts_all_for_2025-12-08.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\TSLA_calls_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-10\\TSLA_puts_all_for_2025-12-10.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\TSLA_calls_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-12\\TSLA_puts_all_for_2025-12-12.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\TSLA_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-15\\TSLA_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\TSLA_calls_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-16\\TSLA_puts_all_for_2025-12-16.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\TSLA_calls_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-17\\TSLA_puts_all_for_2025-12-17.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\TSLA_calls_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-18\\TSLA_puts_all_for_2025-12-18.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\TSLA_calls_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-19\\TSLA_puts_all_for_2025-12-19.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\TSLA_calls_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-23\\TSLA_puts_all_for_2025-12-23.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\TSLA_calls_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-25\\TSLA_puts_all_for_2025-12-25.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\TSLA_calls_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-26\\TSLA_puts_all_for_2025-12-26.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\TSLA_calls_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-29\\TSLA_puts_all_for_2025-12-29.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\TSLA_calls_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-30\\TSLA_puts_all_for_2025-12-30.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\TSLA_calls_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2025-12-31\\TSLA_puts_all_for_2025-12-31.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\TSLA_calls_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-01\\TSLA_puts_all_for_2026-01-01.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\TSLA_calls_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-02\\TSLA_puts_all_for_2026-01-02.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\TSLA_calls_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-05\\TSLA_puts_all_for_2026-01-05.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\TSLA_calls_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-06\\TSLA_puts_all_for_2026-01-06.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\TSLA_calls_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-07\\TSLA_puts_all_for_2026-01-07.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\TSLA_calls_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-08\\TSLA_puts_all_for_2026-01-08.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\TSLA_calls_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-09\\TSLA_puts_all_for_2026-01-09.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\TSLA_calls_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-12\\TSLA_puts_all_for_2026-01-12.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\TSLA_calls_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-13\\TSLA_puts_all_for_2026-01-13.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\TSLA_calls_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-14\\TSLA_puts_all_for_2026-01-14.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\TSLA_calls_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-15\\TSLA_puts_all_for_2026-01-15.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\TSLA_calls_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-16\\TSLA_puts_all_for_2026-01-16.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\TSLA_calls_all_for_2026-01-20.csv', './daily historical datas/Automobile\\Auto_sector_2026-01-20\\TSLA_puts_all_for_2026-01-20.csv']

INFO:utilities:Merged dataset shape: (421080, 16)
INFO:utilities:Removed 156313 duplicates

##### Combine all options data in single dataset

In [14]:
optionsData = pd.DataFrame()

for ticker, dataframe in Finance.items():
  optionsData = merged_df = pd.concat([optionsData, dataframe], ignore_index=True)

for ticker, dataframe in Automobile.items():
  optionsData = merged_df = pd.concat([optionsData, dataframe], ignore_index=True)

for ticker, dataframe in Health.items():
  optionsData = merged_df = pd.concat([optionsData, dataframe], ignore_index=True)

for ticker, dataframe in Technology.items():
  optionsData = merged_df = pd.concat([optionsData, dataframe], ignore_index=True)

In [15]:
len(optionsData)

2114582

In [16]:
optionsData = remove_duplicates(optionsData)

INFO:utilities:Removed 579745 duplicates

In [17]:
len(optionsData)

1534837

##### Preprocess options dataset

In [18]:
optionsData['optionType'] = optionsData['source_file'].str.contains('call').replace({True:'call', False:'put'})

C:\Users\H P\AppData\Local\Temp\ipykernel_36240\262952590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['optionType'] = optionsData['source_file'].str.contains('call').replace({True:'call', False:'put'})

In [19]:
optionsData['date'] = optionsData['lastTradeDate']

C:\Users\H P\AppData\Local\Temp\ipykernel_36240\847214949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['date'] = optionsData['lastTradeDate']

In [20]:
optionsData['date'] = pd.to_datetime(optionsData['date']).dt.date
optionsData['date'] = pd.to_datetime(optionsData['date'])

C:\Users\H P\AppData\Local\Temp\ipykernel_36240\4140904624.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['date'] = pd.to_datetime(optionsData['date']).dt.date
C:\Users\H P\AppData\Local\Temp\ipykernel_36240\4140904624.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['date'] = pd.to_datetime(optionsData['date'])

In [21]:
optionsData['underlyingTicker'] = optionsData['source_file'].str.split('_').str[0]

C:\Users\H P\AppData\Local\Temp\ipykernel_36240\1530006188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['underlyingTicker'] = optionsData['source_file'].str.split('_').str[0]

In [22]:
optionsData['expiration'] = pd.to_datetime(optionsData['expiration'])

C:\Users\H P\AppData\Local\Temp\ipykernel_36240\1268630523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  optionsData['expiration'] = pd.to_datetime(optionsData['expiration'])

In [23]:
start_date = pd.to_datetime('2025-09-12')
last_date = pd.to_datetime('2025-12-12')

optionsData = optionsData[optionsData['date'] >= start_date]
optionsData = optionsData[optionsData['date'] <= last_date]

In [24]:
optionsData['timeToMaturity'] = (optionsData['expiration'] - optionsData['date']).dt.days/365.25
optionsData = optionsData[optionsData['timeToMaturity'] != 0]

##### Handle Put-Call Ratio (PCR) data

In [25]:
df = optionsData

In [26]:
pivot = df.pivot_table(index='date', columns='optionType', values='volume', aggfunc='sum').reset_index()

pivot['PCR'] = pivot.apply(lambda row: row['put']/row['call'] if row['call'] != 0 else None, axis=1)

pivot[['date','call','put','PCR']]

optionType       date          call           put     PCR
0          2025-09-12 4837453.00000 1717121.00000 0.35496
1          2025-09-15 4163745.00000 1928605.00000 0.46319
2          2025-09-16 3318339.00000 1414823.00000 0.42636
3          2025-09-17 3459169.00000 1893364.00000 0.54735
4          2025-09-18 3948063.00000 2105354.00000 0.53326
..                ...           ...           ...     ...
60         2025-12-08 2535660.00000 1481496.00000 0.58426
61         2025-12-09   31000.00000   60932.00000 1.96555
62         2025-12-10 2824790.00000 1371552.00000 0.48554
63         2025-12-11   33805.00000   51771.00000 1.53146
64         2025-12-12 3366108.00000 1453783.00000 0.43189

[65 rows x 4 columns]

In [27]:
pivot = pivot.drop(['call','put'], axis=1)
pivot

optionType       date     PCR
0          2025-09-12 0.35496
1          2025-09-15 0.46319
2          2025-09-16 0.42636
3          2025-09-17 0.54735
4          2025-09-18 0.53326
..                ...     ...
60         2025-12-08 0.58426
61         2025-12-09 1.96555
62         2025-12-10 0.48554
63         2025-12-11 1.53146
64         2025-12-12 0.43189

[65 rows x 2 columns]

In [28]:
pivot.describe()

optionType                           date      PCR
count                                  65 65.00000
mean        2025-10-27 19:56:18.461538560  0.59933
min                   2025-09-12 00:00:00  0.35496
25%                   2025-10-06 00:00:00  0.48206
50%                   2025-10-28 00:00:00  0.52169
75%                   2025-11-19 00:00:00  0.56824
max                   2025-12-12 00:00:00  2.42395
std                                   NaN  0.33282

In [29]:
optionsData = optionsData.merge(pivot, on='date', how='left')

In [30]:
optionsData.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency',
       'expiration', 'source_file', 'optionType', 'date', 'underlyingTicker',
       'timeToMaturity', 'PCR'],
      dtype='object')

##### Handle Google Search (GS) Trend data

In [31]:
gs_folder = "./google search trends data/"

In [32]:
gs_data_finance = pd.read_csv(gs_folder + "Finance.csv")
gs_data_tech = pd.read_csv(gs_folder + "Technology.csv")
gs_data_auto = pd.read_csv(gs_folder + "Automobile.csv")
gs_data_health = pd.read_csv(gs_folder + "Healthcare.csv")

In [33]:
gs_data_finance['date'] = pd.to_datetime(gs_data_finance['date'])
gs_data_tech['date'] = pd.to_datetime(gs_data_tech['date'])
gs_data_auto['date'] = pd.to_datetime(gs_data_auto['date'])
gs_data_health['date'] = pd.to_datetime(gs_data_health['date'])

In [34]:
optionsData = optionsData.merge(gs_data_finance, on='date', how='left')
optionsData = optionsData.merge(gs_data_tech, on='date', how='left')
optionsData = optionsData.merge(gs_data_auto, on='date', how='left')
optionsData = optionsData.merge(gs_data_health, on='date', how='left')

In [35]:
def get_google_search_trends(row):
    ticker = row['underlyingTicker']
    return row["GS_" + ticker]

optionsData['GS'] = optionsData.apply(get_google_search_trends, axis=1)

##### Handle news Sentiment Score (SC) data

In [36]:
sc_folder = "./gdelt news data/"

In [37]:
news_sentiment_score = pd.read_csv(sc_folder + "news_sentiment_score.csv")
news_sentiment_score['date'] = pd.to_datetime(news_sentiment_score['date'])

optionsData = optionsData.merge(news_sentiment_score, on='date', how='left')

In [38]:
optionsData.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency',
       'expiration', 'source_file', 'optionType', 'date', 'underlyingTicker',
       'timeToMaturity', 'PCR', 'GS_BAC', 'GS_C', 'GS_GS', 'GS_JPM', 'GS_WFC',
       'GS_AAPL', 'GS_AMZN', 'GS_GOOGL', 'GS_META', 'GS_MSFT', 'GS_F', 'GS_GM',
       'GS_LCID', 'GS_RIVN', 'GS_TSLA', 'GS_ABBV', 'GS_JNJ', 'GS_MRK',
       'GS_PFE', 'GS_UNH', 'GS', 'SC_AAPL', 'SC_AMZN', 'SC_GOOGL', 'SC_META',
       'SC_MSFT', 'SC_BAC', 'SC_C', 'SC_GS', 'SC_JPM', 'SC_WFC', 'SC_ABBV',
       'SC_JNJ', 'SC_MRK', 'SC_PFE', 'SC_UNH', 'SC_F', 'SC_GM', 'SC_LCID',
       'SC_RIVN', 'SC_TSLA'],
      dtype='object')

In [39]:
def get_underlying_sentiment_score_from(row):
    ticker = row['underlyingTicker']
    return row["SC_" + ticker]

optionsData['SC'] = optionsData.apply(get_underlying_sentiment_score_from, axis=1)

In [40]:
optionsData["SC"]

0         0.10283
1         0.10283
2         0.10283
3         0.10283
4         0.10283
            ...
1088555   0.07455
1088556   0.07443
1088557   0.07455
1088558   0.05093
1088559   0.07455
Name: SC, Length: 1088560, dtype: float64

##### Extract Underlings historical data, VIX, and Interest Rate historical datas

In [41]:
indices_and_equities_underlyings_ticker = TechnologyUnderlying + FinanceUnderlying + HealthUnderlying + AutomobileUnderlying + ["^VIX", "^IRX"]
indices_and_equities_values = {}

for ticker in indices_and_equities_underlyings_ticker:
      data = yf.download(ticker, start=start_date, end=last_date)
      indices_and_equities_values[ticker] = data["Close"]

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [55]:
for ticker in indices_and_equities_values:
  temp = indices_and_equities_values[ticker]
  temp = temp.reset_index()
  temp.columns=['date', ticker]
  optionsData = optionsData.merge(temp, on='date', how='left')

In [58]:
optionsData.columns
#optionsData = optionsData.drop(["GS_x"], axis=1)

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       ...
       'MRK_y', 'PFE_y', 'UNH_y', 'F_y', 'GM_y', 'LCID_y', 'RIVN_y', 'TSLA_y',
       '^VIX_y', '^IRX_y'],
      dtype='object', length=105)

In [57]:
def get_underlying_last_price(row):
    ticker = row['underlyingTicker']
    print(ticker)
    return row[ticker]

optionsData['underlyingLastPrice'] = optionsData.apply(get_underlying_last_price, axis=1)

KeyboardInterrupt:

In [ ]:
optionsData.rename(columns={
    '^IRX': 'riskFreeRate',
    "^VIX": "VIX"
}, inplace=True)

optionsData['riskFreeRate'] = optionsData["riskFreeRate"] / 100
optionsData['impliedVolatility'] = optionsData["impliedVolatility"] / 100

In [ ]:
optionsData["riskFreeRate"].describe()

count   590216.00000
mean         0.03589
std          0.00009
min          0.03570
25%          0.03582
50%          0.03590
75%          0.03595
max          0.03605
Name: riskFreeRate, dtype: float64

##### Save dataset

In [ ]:
from sklearn.model_selection import train_test_split

list_underlyings = [
    "AAPL",
    "AMZN",
    "GOOGL",
    "META",
    "MSFT",
    "BAC",
    "C",
    "GS",
    "JPM",
    "WFC",
    "ABBV",
    "JNJ",
    "MRK",
    "PFE",
    "UNH",
    "F",
    "GM",
    "LCID",
    "RIVN",
    "TSLA"
]

In [ ]:
for ticker in list_underlyings:
      columns_to_keep = [
      "date",
      "lastTradeDate",
      "timeToMaturity",
      "underlyingLastPrice",
      "riskFreeRate",
      "lastPrice",
      "impliedVolatility",
      "strike",
      "PCR",
      "VIX",
      "GS_" + ticker,
      "SC_" + ticker
      ]
      data = optionsData[optionsData["underlyingTicker"] == ticker]
      data = data[[col for col in columns_to_keep if col in data.columns]]
      
      train_data, test_data = train_test_split(data, test_size=0.2, random_state=42 )
      train_data.to_csv("./prepocessed options datas/" + ticker + '_train.csv')
      test_data.to_csv("./prepocessed options datas/"  + ticker + '_test.csv')